/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "EchoServer_constants.h"



const EchoServerConstants g_EchoServer_constants;

EchoServerConstants::EchoServerConstants() {
}



