-- require "main.controller.command.mainScene.MainSceneToLittleHelperCommand";
require "main.controller.command.mainScene.MainSceneToTaskSceneCommand";
require "main.controller.command.mainScene.MainSceneToStrengthenCommand";
-- require "main.controller.command.mainScene.ToChallengeCommand";
require "main.controller.command.mainScene.MainSceneToChatCommand";
require "main.controller.command.mainScene.MainSceneToBuddyCommand";
require "main.controller.command.mainScene.MainSceneToBagCommand";
-- require "main.controller.command.mainScene.MainSceneToPetCommand";
-- require "main.controller.command.mainScene.MainSceneToLookIntoPlayerCommand";
require "main.controller.command.mainScene.MainSceneToFamilyCommand";
-- require "main.controller.command.mainScene.MainSceneToFamilyTaskCommand";
-- require "main.controller.command.mainScene.MainSceneToFirstSevenCommand";
require "main.controller.notification.FamilyNotification";
-- require "main.controller.command.mainScene.MainSceneToStargazingCommand";
require "main.controller.command.mainScene.MainSceneIconEffectCommand";
require "main.controller.command.mainScene.MainSceneIconRefreshCommand";
require "main.controller.command.mainScene.MainSceneChatIconEffectRefreshCommand";
-- require "main.controller.command.mainScene.ToTurntableCommond";
require "main.controller.command.mainScene.MainSceneToMailCommand";