ExcelLua.Tishi_Xiaoxibiao={{"id","title","subID1","uiid","artid","button1","button2","text","addressor","txt"},
key9999={9999,"运营公告",3,0,0,"","","","",""},
key1={1,"论剑排名奖励",4,0,0,"","","来领取排名奖励啦！截止发奖你的排名是@1，获得了排名奖励！加油吧！","夏冬姐姐",""},
key2={2,"月卡元宝发放",4,0,0,"","","亲爱的快来领工资啦！月卡发放啦~领取每日可收的@1元宝咯！","苏哥哥",""},
key3={3,"欢迎来到琅琊榜",4,0,0,"","","一卷风云琅琊榜，囊尽天下奇英才.....欢迎进入琅琊榜的世界！关注官方微博【琅琊榜游戏】；官方微信【琅琊榜手游】领取新手礼包哦！登陆官网还有惊喜赠送~！","苏哥哥",""},
key4={4,"论剑提升奖励",4,0,0,"","","你的排名提升到了@1，获得了提升奖励！","夏冬姐姐",""},
key5={5,"吃午餐领体力咯【限时】",5,0,0,"","","孩子们，来吃饺子咯！人是铁饭是钢，午餐不吃饿得慌，吃完吉婶的饺子，立马儿恢复60体力，注意时间是11:00~14:00~啊！","吉婶",""},
key6={6,"吃晚餐领体力咯【限时】",5,0,0,"","","孩子们，吃晚饭啦！夜不多食，咱吃点儿素饺子喝点红豆汤，一天辛劳一扫光，马上恢复60体力，注意时间是17:00~20:00~啊！","吉婶",""},
key8={8,"角色进阶",3,0,0,"","","<content><font color='#ffffff'>大吉大利，</font><font color='#fff600'>@1</font><font color='#ffffff'>将</font><font color='#ffa800'>@2</font><font color='#ffffff'>进阶到橙色品质</font></content>","","ffffff#大吉大利,;fff600#@1;ffffff#将;ffa800#@2;ffffff#进阶到橙色品质"},
key9={9,"论剑第三名",3,0,0,"","","<content><font color='#ffffff'>势头强劲，</font><font color='#fff600'>@1</font><font color='#ffffff'>在论剑中赢得了第三名</font></content>","","ffffff#势头强劲,;fff600#@1;ffffff#在论剑中赢得了第三名"},
key10={10,"论剑第二名",3,0,0,"","","<content><font color='#ffffff'>实力超群，</font><font color='#fff600'>@1</font><font color='#ffffff'>在论剑中赢得了第二名</font></content>","","ffffff#实力超群,;fff600#@1;ffffff#在论剑中赢得了第二名"},
key11={11,"论剑第一名",3,0,0,"","","<content><font color='#ffffff'>天下无敌，</font><font color='#fff600'>@1</font><font color='#ffffff'>在论剑中赢得了第一名</font></content>","","ffffff#天下无敌,;fff600#@1;ffffff#在论剑中赢得了第一名"},
key12={12,"十国征战通关",3,0,0,"","","<content><font color='#ffffff'>勇士</font><font color='#fff600'>@1</font><font color='#ffffff'>披荆斩棘征战十国，凯旋通关，实则国栋！</font></content>","","ffffff#勇士;fff600#@1;ffffff#披荆斩棘征战十国,凯旋通关,实则国栋！"},
key13={13,"朝堂争辩完美",3,0,0,"","","<content><font color='#ffffff'>国之重本必将文武俱在，恭贺</font><font color='#fff600'>@1</font><font color='#ffffff'>在朝堂争辩获得完美通过！</font></content>","","ffffff#国之重本必将文武俱在,恭贺;fff600#@1;ffffff#在朝堂争辩获得完美通过！"},
key14={14,"官职达到xx",3,0,0,"","","<content><font color='#ffffff'>升官进爵尤为可贺，恭喜</font><font color='#fff600'>@1</font><font color='#ffffff'>官职升为</font><font color='#fff600'>@2</font></content>","","ffffff#升官进爵尤为可贺,恭喜;fff600#@1;ffffff#官职升为;fff600#@2"},
key15={15,"背包快满了",4,0,0,"","","背包就要满咯，满后将会得不到任何奖励和掉落哦，去清理一下吧！","苏哥哥",""},
key16={16,"背包已满快清理",4,0,0,"","","背包满了啊，满后将会得不到任何奖励和掉落哦，去清理一下吧！","苏哥哥",""},
key17={17,"创建帮派推送",1,0,0,"","","","","00fffc#@1;ffffff#创建了帮派;00fffc#@2;ffffff#，诚邀小伙伴！;18ff00#点击申请"},
key18={18,"酒宴结束得体力",4,0,0,"","","帮派酒宴@1结束了，吃的饱饱的真舒服呢，获得@2体力，感谢宴会主人@3！","飞流弟弟",""},
key19={19,"举办酒宴推送",3,0,0,"","","<content><font color='#ffffff'>帮派大壕</font><font color='#fff600'>@1</font><font color='#ffffff'>举办了一场</font><font color='#fff600'>@2</font><font color='#ffffff'>酒宴，快去抢位置呀，跟着大哥混！</font></content>","","ffffff#帮派大壕;fff600#@1;ffffff#举办了场;fff600#@2;ffffff#酒宴，快去抢位置，;18ff00#点击加入"},
key20={20,"酒宴邀请",1,0,0,"","","<content><font color='#ffffff'>帮派大壕</font><font color='#fff600'>@1</font><font color='#ffffff'>举办了一场</font><font color='#fff600'>@2</font><font color='#ffffff'>酒宴，邀请小伙伴们来一起吃喝，快来参加！</font></content>","","00fffc#@1;ffffff#举办了场;fff600#@2;ffffff#酒宴，邀请小伙伴们一起吃喝，;18ff00#点击加入"},
key21={21,"帮派招人推送",1,0,0,"","","","","00fffc#@1;ffffff#的帮派;00fffc#@2;ffffff#，诚邀小伙伴！;18ff00#点击申请"},
key22={22,"全帮酒宴推送",1,0,0,"","","<content><font color='#ffffff'>帮派大壕</font><font color='#fff600'>@1</font><font color='#ffffff'>举办了一场</font><font color='#fff600'>@2</font><font color='#ffffff'>酒宴，普天同庆快去领体力！</font></content>","","ffffff#帮派大壕;fff600#@1;ffffff#举办了一场;fff600#@2;ffffff#酒宴，普天同庆快去邮件领体力！"},
key23={23,"佣兵收入",4,0,0,"","","你离开了帮派，派出去的佣兵回家了，来领取佣兵的辛苦钱吧！","秋长老-莫之过",""},
key24={24,"离开帮派了",4,0,0,"","","你已经离开了帮派@1哦。。。。加入新的帮派吧！","苏哥哥",""},
key25={25,"历史累计签到奖励",4,0,0,"","","恭喜您累计签到获得@1；再签到@2天即可获得@3哦~","苏哥哥",""},
key26={26,"论剑任务奖励",4,0,0,"","","发放任务奖励啦！你完成了一个论剑任务，获得了丰厚的奖励哦！","夏冬姐姐",""},
key27={27,"有奖竞答排名奖励",4,0,0,"","","恭喜你获得今日有奖竞答活动第@1名！","夏冬姐姐",""},
key28={28,"VIP每日有礼【扫荡券】",4,0,0,"","","尊贵的VIP大人，今日的扫荡券已经奉上，请查收。","小津",""},
key29={29,"好友赠送鲜花啦",4,0,0,"","","你的好友@1送了你@2，获得@3经验，真喜欢他呢。","好友系统",""},
key30={30,"好友赠送体力啦",4,0,0,"","","你的好友@1送了你2点体力，赶快领取吧~","好友系统",""}}