
MainSceneNotifications={
						TO_BATTLE="mainSceneToBattle",
						TO_BAG="mainSceneToBag",
						CLICK_MENU="CLICK_MENU",
						TO_ROLENAME="TO_ROLENAME",
						TO_LITTLEHELPER="TO_LITTLEHELPER",
						TO_VIP="mainSceneToVip",
						TO_TASK="mainSceneToTask",
						TO_CHEAT="mainSceneToCheat",
						TO_STRENGTHEN="mainToStrengthen",
						TO_TOWER="mainSceneToTower",
						TO_HEROMAPS="mainSceneToHeroMaps",
						TO_EVERYDAY_TASK="mainSceneToEverydayTask",
						TO_PETBANKUI="ToPetBankUI",
						TO_CHAT="mainSceneToChat",
						TO_BUDDY="mainSceneToBuddy",
						TO_AVATAR="mainSceneToAvatar",
						TO_COMBAT_PET="mainSceneToCombatPet",
						TO_PET_AND_ROLL="mainSceneToPetAndRoll",
						TO_PET="ToPet",
						TO_CHALLENGE = "TO_CHALLENGE",
						TO_ADD_TILI = "TO_ADD_TILI",
						TO_REMOVE_TILI = "TO_REMOVE_TILI",
						TO_OPERATION = "TO_OPERATION",
						TO_LOOK_INTO_PLAYER="mainSceneToLookIntoPlayer",
						TO_ACHIEVEMENT="mainSceneToAchievement",
						TO_SYSTEM_MARK="mainSceneToSystemMark",
						TO_TITLE="mainSceneToTitle",
						TO_LOGIN_LOTTERY="mainSceneToLoginLottery",
						TO_ACTIVITY="mainSceneToActivity",
						TO_SMALL_CHAT="mainSceneToSmallChat",
						TO_OPERATION_RECORD="TO_OPERATION_RECORD",
						TO_CLOSE_MAINSCENE="TO_CLOSE_MAINSCENE",
						TO_SAVE_POSITION_INFO="TO_SAVE_POSITION_INFO",
					    TO_OTHER_PLAYER_MENU="TO_OTHER_PLAYER_MENU",
						TO_STARGAZING="TO_STARGAZING",
						TO_OPEN_TUTOR_UI="TO_OPEN_TUTOR_UI",
						TO_FUNCTION_OPEN_EFFECT="TO_FUNCTION_OPEN_EFFECT",
						TO_OPEN_PRIVATE_CHAT="TO_OPEN_PRIVATE_CHAT",
						TO_SHOP_FLIP="mainSceneToShopFlip",
						TO_BUG_REPORT="mainSceneToBugReport",
						TO_HANG_UP="TO_HANG_UP",
						TO_REMOVE_HANG_UP="TO_REMOVE_HANG_UP",
						TO_REMOVE_OPERATION="TO_REMOVE_OPERATION",
						TO_REMOVE_GUANGBO="TO_REMOVE_GUANGBO",
						MAIN_SCENE_TO_FAMILY="mainSceneToFamily",
						MAIN_SCENE_TO_TASK="mainSceneToTask",
						MAIN_SCENE_TO_FIRST_SEVEN="mainSceneToFirstSeven",
						TO_TEAM_SHADOW="TO_TEAM_SHADOW",
						REFRESH_CHAT_ICON_EFFECT="refreshChatIconEffect",
						MAIN_SCENE_TO_FIRST_CHARGE_UI="MAIN_SCENE_TO_FIRST_CHARGE_UI",
						OPEN_PLATFORM_CHARGE_UI_COMMAND="OPEN_PLATFORM_CHARGE_UI_COMMAND",
						MAIN_SCENE_TO_OPERATION_BONUS="mainSceneToOperationBonus",
						MAIN_SCENE_TO_MONSTER_BATTLE="mainSceneToMonsterBattle",
						MAIN_SCENE_TO_AMASS_FORTUNES="MAIN_SCENE_TO_AMASS_FORTUNES",
						MAIN_SCENE_TO_FUND="MAIN_SCENE_TO_FUND",
						MAIN_SCENE_TO_LIMITED_SUMMON_HERO="MAIN_SCENE_TO_LIMITED_SUMMON_HERO",
						MAIN_SCENE_TO_ICON_REFRESH="MAIN_SCENE_TO_ICON_REFRESH",
						DUEL_OTHER_PLAYER="DUEL_OTHER_PLAYER",
						MAIN_SCENE_TO_POSSESSION_BATTLE="mainSceneToPossessionBattle",
						MAIN_SCENE_TO_CHANGE_NAME="mainSceneToNameChange",
						MAIN_SCENE_TO_MAP_WORLD="MAIN_SCENE_TO_MAP_WORLD",
						CLOSE_MAP_WORLD="CLOSE_MAP_WORLD",
						TO_ADD_SEVICEPANEL="TO_ADD_SEVICEPANEL",
						TO_REMOVE_SEVICEPANEL="TO_REMOVE_SEVICEPANEL",
						MAIN_SCENE_TO_MAIL="mainSceneToMail",
						TO_HEROHOUSE="TO_HEROHOUSE",
						TO_HEROJINJIE="TO_HEROJINJIE",
						TO_HEROPRO="TO_HEROPRO",
						TO_HEROSHENGJI="TO_HEROSHENGJI",
						TO_HEROSKILL="TO_HEROSKILL",
						TO_HEROTEAMMAIN="TO_HEROTEAMMAIN",
						TO_HEROTEAMSUB="TO_HEROTEAMSUB",
						TO_HEROCHANGEEQUIPE="TO_HEROCHANGEEQUIPE",
						TO_ADD_BUTTON_GROUP_COMMAND="TO_ADD_BUTTON_GROUP_COMMAND",
						TO_ADD_LEFT_BUTTON_GROUP_COMMAND="TO_ADD_LEFT_BUTTON_GROUP_COMMAND",
						TO_REMOVE_LEFT_BUTTON_GROUP_COMMAND="TO_REMOVE_LEFT_BUTTON_GROUP_COMMAND",
						TO_ADD_CURRENCY_GROUP_COMMAND="TO_ADD_CURRENCY_GROUP_COMMAND",
						TO_REMOVE_BUTTON_GROUP_COMMAND="TO_REMOVE_BUTTON_GROUP_COMMAND",
						TO_REMOVE_CURRENCY_GROUP_COMMAND="TO_REMOVE_CURRENCY_GROUP_COMMAND",
						TO_ADD_HBUTTON_GROUP_COMMAND="TO_ADD_HBUTTON_GROUP_COMMAND",
						TO_REMOVE_HBUTTON_GROUP_COMMAND="TO_REMOVE_HBUTTON_GROUP_COMMAND",
						TO_OPEN_MENU_COMMAND="TO_OPEN_MENU_COMMAND",
						TO_CLOSE_MENU_COMMAND="TO_CLOSE_MENU_COMMAND",
						TO_CREATE_ROLE_COMMAND="TO_CREATE_ROLE_COMMAND",
						TO_RANK_LIST="TO_RANK_LIST",
						TO_ARENA="TO_ARENA",
						MAIN_SCENE_TO_GUANZHI="MAIN_SCENE_TO_GUANZHI",
						TO_OPEN_HAND_OF_MIDAS_UI="TO_OPEN_HAND_OF_MIDAS_UI",
						TO_CLOSE_HAND_OF_MIDAS_UI="TO_CLOSE_HAND_OF_MIDAS_UI",
						TO_ADD_FUNCTION_OPEN_UI="TO_ADD_FUNCTION_OPEN_UI",
						TO_CLOSE_FUNCTION_OPEN_UI="TO_CLOSE_FUNCTION_OPEN_UI",
						TO_REFRESH_REDDOT="TO_REFRESH_REDDOT",
						TO_TRACK_ITEM_UI_COMMAND="TO_TRACK_ITEM_UI_COMMAND",
						CLOSE_TRACK_ITEM_UI_COMMAND="CLOSE_TRACK_ITEM_UI_COMMAND",
						TO_YONG_BING = "TO_YONG_BING",
						TO_HUANHUA_UI_COMMAND="TO_HUANHUA_UI_COMMAND",
						CLOSE_HUANHUA_UI_COMMAND = "CLOSE_HUANHUA_UI_COMMAND",
						TO_TIANXIANG_UI_COMMAND="TO_TIANXIANG_UI_COMMAND",
						CLOSE_TIANXIANG_UI_COMMAND = "CLOSE_TIANXIANG_UI_COMMAND"
						};

MainSceneNotification=class(Notification);

function MainSceneNotification:ctor(type_string, data)
	self.class=MainSceneNotification;
	self.type=type_string;
	self.data=data;
end

function MainSceneNotification:getData()
  return self.data;
end

--玩家名称
function MainSceneNotification:getPlayerName()
	if self.data then
	  return self.data.playerName;
	end
	return "";
end

--玩家ID
function MainSceneNotification:getPlayerID()
	if self.data then
	  return self.data.playerID;
	end
	return 0;
end