/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EchoServer_CONSTANTS_H
#define EchoServer_CONSTANTS_H

#include "EchoServer_types.h"



class EchoServerConstants {
 public:
  EchoServerConstants();

};

extern const EchoServerConstants g_EchoServer_constants;



#endif
