#ifndef MOF_BAGUI_H
#define MOF_BAGUI_H

class BagUI{
public:
	void showFashionDesc(void);
	void clearBagItems(void);
	void onMenuItemRaiseClicked(cocos2d::CCObject *);
	void onMenuItemEquipClicked(cocos2d::CCObject *);
	void freshFashionTableView(int);
	void hideMakeSureDialog(void);
	void changeBodyFashion(void);
	void freshWardrobeExp(int, int);
	void freshWardrobeExp(int,int);
	void showPetNode(PetMonster	*, int,	int, int);
	void setTitleCancel(bool);
	void onMenuItemSellFashionClicked(cocos2d::CCObject *);
	void editBoxTextChanged(cocos2d::extension::CCEditBox	*, std::string const&);
	void refreshTitle(void);
	void closeExpProgressEffect(float);
	void jumpToTitle(int);
	void detectionInputStr(void);
	void onMenuItemMinClicked(cocos2d::CCObject	*);
	void setCurrentWeaponFashionid(int);
	void setscrollSpritePostion(int);
	void onAssignCCBMemberVariable(cocos2d::CCObject *,	char const*, cocos2d::CCNode *);
	void onMenuItemCloseFashionEffectClicked(cocos2d::CCObject *);
	void recv(int,void *);
	void onRenameMenuItemCloseClick(cocos2d::CCObject *);
	void hideRenameDialog(void);
	void registerWithTouchDispatcher(void);
	void editBoxEditingDidBegin(cocos2d::extension::CCEditBox *);
	void setEquipmentDesc(EquipInfo);
	void ccTouchMoved(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void setmagicValue(void);
	void onMenuItemToCellClicked(cocos2d::CCObject *);
	void onPetNodeMenuItemCloseClicked(cocos2d::CCObject	*);
	void Init(void);
	void onMenuItemWeaponFashionClicked(cocos2d::CCObject *);
	void setFashionShowImage(EquipInfo,bool);
	void openEquipStrengthUI(void);
	void initTitleUI(void);
	void setEquipTipsPostion(int,bool);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject	*,char const*);
	void getCurrentWeaponFashionid(void);
	void getCurrentBadyFashionid(void)const;
	void isShowNewDropEquipTips(void);
	void onMenuItemReanameCancelClicked(cocos2d::CCObject *);
	void freshWardrobeAddValue(int);
	void init(void);
	void showStrengthEffect(void);
	void setMultipleTipsShowImage(bool);
	void onMenuItemCancelUseTitleClicked(cocos2d::CCObject *);
	void ccTouchCancelled(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void freshExpProgressCallback(float);
	void showFashinAddValue(int);
	void onMenuItemMinClicked(cocos2d::CCObject *);
	void showPetNode(PetMonster	*,int,int,int);
	void showFashionDesc(int, BodyPart);
	void showNewDropEquipTips(int);
	void setTipsShowImage(bool);
	void showWardrobeAddExpEffect(int, int);
	void showStrengthVolley(void);
	void onMenuItemCloseQualityVolleyClicked(cocos2d::CCObject *);
	void setCurrentBadyFashionid(int);
	void initeMultiplEquipmentTip(void);
	void hideToCelldialog(void);
	void showWardrobeAddExpEffect(int,int);
	void getAddValueDesc(ItemCfgDef *);
	void showGuildGadDesc(void);
	void onMenuItemEquipmentClicked(cocos2d::CCObject *);
	void showEquipmentDesc(EquipInfo,equipmentTip);
	void recv(int, int, cocos2d::CCPoint,	int);
	void recv(int,int,cocos2d::CCPoint,int);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *,char const*);
	void onMenuItemTakeOffClicked(cocos2d::CCObject *);
	void onPetNodeMenuItemCloseClicked(cocos2d::CCObject *);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject	*, char	const*);
	void getClickedFashion(void);
	void showNameHasEixsit(int);
	void recv(int, int, char const*);
	void changeMainRoleCloth(BodyPart, int);
	void initequippostion(void);
	void expLabelMoveToCallback(cocos2d::CCNode *);
	void onMenuItemFashionClicked(cocos2d::CCObject *);
	void onEnter(void);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *,char	const*);
	void onMenuItemClearUpClicked(cocos2d::CCObject *);
	void showQualityEffect(void);
	void initequipmentTip(void);
	void onMenuItemWillOpenPetClicked(cocos2d::CCObject *);
	void onRenameMenuItemClick(cocos2d::CCObject	*);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *, char const*);
	void ccTouchMoved(cocos2d::CCTouch *,cocos2d::CCEvent	*);
	void recv(int,int,char const*);
	void onMenuItemSellFashionClicked(cocos2d::CCObject	*);
	void onAssignCCBMemberVariable(cocos2d::CCObject *,char const*,cocos2d::CCNode *);
	void getCurrentWeaponFashionid(void)const;
	void ~BagUI();
	void onControlStrDescClicked(cocos2d::CCObject *,uint);
	void onMenuItemTitleClicked(cocos2d::CCObject *);
	void hideStrDescNode(void);
	void sellEquipItem(void);
	void openPetAbsortedUI(void);
	void editBoxTextChanged(cocos2d::extension::CCEditBox *, std::string const&);
	void refreshName(void);
	void onExit(void);
	void showPetCollectNode(int,IllustrationsQuality);
	void setTitleSeled(int);
	void CreateEquipmentUI(void);
	void showMultipleEquipmentDesc(EquipInfo,multipleEquipTip &,int,int,bool);
	void showPetCollectNode(int, IllustrationsQuality);
	void setUseTitleEnabled(bool);
	void onMenuItemOpeningPetClicked(cocos2d::CCObject *);
	void ccTouchEnded(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void onMenuItemFashionDescClicked(cocos2d::CCObject	*);
	void onMenuItemStrengthVolleyClicked(cocos2d::CCObject *);
	void onMenuItemCancelClicked(cocos2d::CCObject *);
	void showRenameDialog(void);
	void onPetCollectUpdateClicked(cocos2d::CCObject *);
	void onMenuItemLeftClicked(cocos2d::CCObject	*);
	void onMenuItemQualityVolleyClicked(cocos2d::CCObject *);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void editBoxTextChanged(cocos2d::extension::CCEditBox	*,std::string const&);
	void showEquipmentDesc(EquipInfo, equipmentTip);
	void showUseItmeOpenEffect(int);
	void setFashionShowImage(EquipInfo,	bool);
	void BagUI(void);
	void onRenameMenuItemClick(cocos2d::CCObject *);
	void onMenuItemCloseStrengthVolleyClicked(cocos2d::CCObject	*);
	void showFashionModel(int,int);
	void takeOffEquipment(int);
	void onMenuItemFashionDescClicked(cocos2d::CCObject *);
	void onControlStrDescClicked(cocos2d::CCObject *, unsigned int);
	void addEquipmentMeu(int,int);
	void setFashionNodeIsShow(bool);
	void addEquipmentMeu(int, int);
	void onMenuItemWillOpenPetClicked(cocos2d::CCObject	*);
	void showMultipleEquipmentDesc(EquipInfo, multipleEquipTip &, int, int, bool);
	void changeMainRoleCloth(BodyPart,int);
	void setLifeValue(void);
	void onMenuItemMaxClicked(cocos2d::CCObject	*);
	void onMenuItemPropertyClicked(cocos2d::CCObject *);
	void onMenuItemCloseClicked(cocos2d::CCObject *);
	void setBadyFashionImageEnable(bool);
	void recv(int, int,	char const*);
	void onMenuItemMaxClicked(cocos2d::CCObject *);
	void ccTouchMoved(cocos2d::CCTouch *,	cocos2d::CCEvent *);
	void ccTouchCancelled(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void getClickedFashion(void)const;
	void showToCelldialog(bool);
	void setEquipmentHide(bool);
	void setEquipDescTipsHide(void);
	void setClickedFashion(int);
	void onMenuItemLeftClicked(cocos2d::CCObject *);
	void onMenuItemGuildGadClick(cocos2d::CCObject *);
	void ccTouchEnded(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void editBoxReturn(cocos2d::extension::CCEditBox *);
	void onMenuItemConfirmClicked(cocos2d::CCObject *);
	void getCurrentBadyFashionid(void);
	void getWardrobeDesc(int);
	void showFashionDesc(int,BodyPart);
	void onMenuItemBadyFashionClicked(cocos2d::CCObject *);
	void setEquipTipsPostion(int, bool);
	void checkPetByNewguidance(cocos2d::CCPoint);
	void onMenuItemUseTitleClicked(cocos2d::CCObject *);
	void onMenuItemNextWardrobeAddDescClicked(cocos2d::CCObject *);
	void recv(int, int,	cocos2d::CCPoint, int);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *,char const*);
	void ccTouchEnded(cocos2d::CCTouch *,	cocos2d::CCEvent *);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void onGoToPetUIClicked(cocos2d::CCObject *);
	void recv(int, void *);
	void expLabelMoveToCallback(cocos2d::CCNode	*);
	void setAllpropertyValue(void);
	void onMenuItemGoToPetAbsortedUI(cocos2d::CCObject *);
	void onAssignCCBMemberVariable(cocos2d::CCObject *, char const*, cocos2d::CCNode *);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *, char const*);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent	*);
	void onMenuItemBadyFashionClicked(cocos2d::CCObject	*);
	void recv(int, void	*);
	void StrengthenIsOpen(void);
	void setToCellNum(void);
	void showMakeSureDailog(void);
	void onMenuItemRightClicked(cocos2d::CCObject *);
	void initGuildGad(void);
	void hideChangeNameCCNode(void);
	void ccTouchMoved(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void hideDesc(void);
	void adjustScrollView(cocos2d::extension::CCScrollView *, int, int *);
	void setCurTitleShow(void);
	void startPlayExpEffect(void);
	void accountInputDetection(void);
	void setEquipFightingShow(EquipInfo,int);
	void showStrDescNode(void);
	void onMenuItemNextWardrobeAddDescClicked(cocos2d::CCObject	*);
	void editBoxEditingDidEnd(cocos2d::extension::CCEditBox *);
	void changeWeapFashion(int);
	void editBoxTextChanged(cocos2d::extension::CCEditBox *,std::string	const&);
	void adjustScrollView(cocos2d::extension::CCScrollView *,int,int *);
	void create(void);
	void onMenuItemStartClicked(cocos2d::CCObject *);
	void openPetEgeByNewguidance(int);
	void onMenuItemCloseStrengthVolleyClicked(cocos2d::CCObject *);
	void ccTouchBegan(cocos2d::CCTouch *,	cocos2d::CCEvent *);
	void ccTouchEnded(cocos2d::CCTouch *,cocos2d::CCEvent	*);
	void onMenuItemBuyFashinClicked(cocos2d::CCObject *);
	void setEquipFightingShow(EquipInfo, int);
	void showQualityVolley(void);
	void delNewDropEquipTips(int);
}
#endif