#ifndef MOF_CCPARTICLESYSTEM_H
#define MOF_CCPARTICLESYSTEM_H

class CCParticleSystem{
public:
	void getRotatePerSecond(void);
	void setBlendFunc(cocos2d::_ccBlendFunc);
	void setAtlasIndex(uint);
	void getRotatePerSecondVar(void);
	void setRadialAccelVar(float);
	void getPosVar(void);
	void isBlendAdditive(void);
	void setTangentialAccelVar(float);
	void setStartRadiusVar(float);
	void setSourcePosition(cocos2d::CCPoint	const&);
	void setTotalParticles(uint);
	void getGravity(void);
	void updateBlendFunc(void);
	void getTexture(void);
	void setStartSizeVar(float);
	void getStartColorVar(void);
	void setEndSizeVar(float);
	void setEndSize(float);
	void CCParticleSystem(void);
	void setSpeed(float);
	void setTexture(cocos2d::CCTexture2D *);
	void getLifeVar(void);
	void getEndRadiusVar(void);
	void setSpeedVar(float);
	void getTangentialAccelVar(void);
	void init(void);
	void setStartSpin(float);
	void getPositionType(void);
	void setEndRadiusVar(float);
	void setTangentialAccel(float);
	void setRotatePerSecondVar(float);
	void setPosVar(cocos2d::CCPoint	const&);
	void setEmitterMode(int);
	void getStartSpin(void);
	void setAtlasIndex(unsigned int);
	void isAutoRemoveOnFinish(void);
	void getEndSizeVar(void);
	void getEmissionRate(void);
	void getSpeedVar(void);
	void setDuration(float);
	void getEndSize(void);
	void setEndSpinVar(float);
	void postStep(void);
	void isActive(void);
	void getStartSize(void);
	void getStartColor(void);
	void setAngle(float);
	void getEndColorVar(void);
	void setStartRadius(float);
	void setRadialAccel(float);
	void getAngle(void);
	void setBatchNode(cocos2d::CCParticleBatchNode *);
	void getStartRadiusVar(void);
	void setStartSize(float);
	void setRotatePerSecond(float);
	void initWithTotalParticles(uint);
	void setAngleVar(float);
	void getEndSpinVar(void);
	void addParticle(void);
	void setStartSpinVar(float);
	void setScaleY(float);
	void getSourcePosition(void);
	void initParticle(cocos2d::sCCParticle *);
	void setRotation(float);
	void getEndColor(void);
	void setLifeVar(float);
	void getRadialAccelVar(void);
	void getTotalParticles(void);
	void initWithTotalParticles(unsigned int);
	void getOpacityModifyRGB(void);
	void setEmissionRate(float);
	void getEmitterMode(void);
	void setEndColorVar(cocos2d::_ccColor4F	const&);
	void setEndColor(cocos2d::_ccColor4F const&);
	void getRadialAccel(void);
	void ~CCParticleSystem();
	void getStartRadius(void);
	void getAtlasIndex(void);
	void getDuration(void);
	void getBatchNode(void);
	void getTangentialAccel(void);
	void getEndSpin(void);
	void getBlendFunc(void);
	void setPositionType(cocos2d::tCCPositionType);
	void getStartSizeVar(void);
	void updateQuadWithParticle(cocos2d::sCCParticle *,cocos2d::CCPoint const&);
	void setOpacityModifyRGB(bool);
	void setAutoRemoveOnFinish(bool);
	void setEndSpin(float);
	void setGravity(cocos2d::CCPoint const&);
	void getStartSpinVar(void);
	void update(float);
	void updateQuadWithParticle(cocos2d::sCCParticle *, cocos2d::CCPoint const&);
	void setLife(float);
	void getParticleCount(void);
	void setScale(float);
	void getLife(void);
	void setStartColorVar(cocos2d::_ccColor4F const&);
	void setStartColor(cocos2d::_ccColor4F const&);
	void getAngleVar(void);
	void updateWithNoTime(void);
	void setBlendAdditive(bool);
	void setEndRadius(float);
	void setScaleX(float);
	void setTotalParticles(unsigned	int);
	void getEndRadius(void);
	void getSpeed(void);
}
#endif