#ifndef MOF_COCOS2D_H
#define MOF_COCOS2D_H

class cocos2d{
public:
	void unz64local_getLong64(cocos2d::zlib_filefunc64_32_def_s const*, void *, unsigned long	long *);
	void unz64local_getByte(cocos2d::zlib_filefunc64_32_def_s	const*,	void *,	int *);
	void CCLog(char const*,...);
	void ccGLBindTexture2D(unsigned int);
	void fclose_file_func(void *,void	*);
	void ccArrayNew(unsigned int);
	void ccCArrayRemoveValueAtIndex(cocos2d::_ccCArray *, unsigned int);
	void ccpDistance(cocos2d::CCPoint	const&,	cocos2d::CCPoint const&);
	void ccGLDeleteProgram(uint);
	void ftell64_file_func(void *,void	*);
	void unzGoToFirstFile64(void *, cocos2d::unz_file_info64_s *, char *, unsigned long);
	void splitWithForm(char const*,std::vector<std::string,std::allocator<std::string>> &);
	void unzCloseCurrentFile(void *);
	void ccGLDeleteProgram(unsigned int);
	void ccCArrayContainsValue(cocos2d::_ccCArray *,void *);
	void ccNextPOT(ulong);
	void call_ztell64(cocos2d::zlib_filefunc64_32_def_s const*, void *);
	void fopen64_file_func(void *,void const*,int);
	void ccArrayRemoveObject(cocos2d::_ccArray *,cocos2d::CCObject *,bool);
	void ccCArrayRemoveValue(cocos2d::_ccCArray *,void *);
	void unzGetCurrentFileInfo(void *,cocos2d::unz_file_info_s *,char	*,ulong,void *,ulong,char *,ulong);
	void ccCArrayFree(cocos2d::_ccCArray *);
	void ccCArrayRemoveValue(cocos2d::_ccCArray *, void *);
	void CCPoint *>(false,	false, std::random_access_iterator_tag);
	void ccCArrayNew(uint);
	void CCAffineTransformTranslate(cocos2d::CCAffineTransform const&,float,float);
	void ccArrayInsertObjectAtIndex(cocos2d::_ccArray	*, cocos2d::CCObject *,	unsigned int);
	void fopen64_file_func(void *, void const*, int);
	void CCRectApplyAffineTransform(cocos2d::CCRect const&,cocos2d::CCAffineTransform	const&);
	void ccpLineIntersect(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint	const&,	float *, float *);
	void fwrite_file_func(void *,void	*,void const*,ulong);
	void GLToClipTransform(kmMat4 *);
	void fseek64_file_func(void *,void *,ulong long,int);
	void clampf(float,float,float);
	void CCAffineTransformConcat(cocos2d::CCAffineTransform const&, cocos2d::CCAffineTransform const&);
	void ccGLDeleteTexture(uint);
	void unzGoToNextFile(void	*);
	void unzReadCurrentFile(void *, void *, unsigned int);
	void ccArrayGetIndexOfObject(cocos2d::_ccArray *,	cocos2d::CCObject *);
	void ccArrayAppendObject(cocos2d::_ccArray *, cocos2d::CCObject *);
	void ccpNormalize(cocos2d::CCPoint const&);
	void unz64local_GetCurrentFileInfoInternal(void *,cocos2d::unz_file_info64_s *,cocos2d::unz_file_info64_internal_s *,char	*,ulong,void *,ulong,char *,ulong);
	void ccArrayGetIndexOfObject(cocos2d::_ccArray *,cocos2d::CCObject *);
	void __CCAffineTransformMake(float, float, float);
	void FNTConfigRemoveCache(void);
	void __CCAffineTransformMake(float,float,float,float,float,float);
	void call_zopen64(cocos2d::zlib_filefunc64_32_def_s const*, void const*, int);
	void fread_file_func(void	*, void	*, void	*, unsigned long);
	void ccpLerp(cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
	void unzOpenInternal(void	const*,	cocos2d::zlib_filefunc64_32_def_s *, int);
	void unz64local_getShort(cocos2d::zlib_filefunc64_32_def_s const*,void *,ulong *);
	void getXMLNodeForKey(char const*,_xmlNode **);
	void ftell64_file_func(void *, void *);
	void fread_file_func(void	*,void *,void *,ulong);
	void ccGLBindVAO(unsigned	int);
	void ftell64_file_func(void *,void *);
	void ccGLBindTexture2DN(unsigned int, unsigned int);
	void ccGLEnableVertexAttribs(unsigned int);
	void ccSetProjectionMatrixDirty(void);
	void unzOpenCurrentFile(void *);
	void ccNextPOT(unsigned long);
	void ccArrayInsertObjectAtIndex(cocos2d::_ccArray	*,cocos2d::CCObject *,uint);
	void CCRectApplyAffineTransform(cocos2d::CCRect const&, cocos2d::CCAffineTransform const&);
	void unzOpen(char	const*);
	void ccArrayContainsObject(cocos2d::_ccArray *, cocos2d::CCObject	*);
	void unz64local_getLong(cocos2d::zlib_filefunc64_32_def_s	const*,void *,ulong *);
	void ccpClamp(cocos2d::CCPoint const&,cocos2d::CCPoint const&,cocos2d::CCPoint const&);
	void ccArrayRemoveObjectAtIndex(cocos2d::_ccArray	*, unsigned int, bool);
	void ferror_file_func(void	*,void *);
	void unzOpenCurrentFile3(void *, int *, int *, int, char const*);
	void ccGLEnable(cocos2d::ccGLServerState);
	void ccGLBlendFunc(unsigned int, unsigned	int);
	void ccGLBindVAO(uint);
	void ccGLBlendFunc(uint,uint);
	void CCLog(char const*, ...);
	void ccCArrayInsertValueAtIndex(cocos2d::_ccCArray *, void *, unsigned int);
	void ccGLInvalidateStateCache(void);
	void showPlatformDialog(char const*, char	const*,	char const*, char const*, cocos2d::DialogType);
	void call_zseek64(cocos2d::zlib_filefunc64_32_def_s const*,void *,ulong long,int);
	void fread_file_func(void *,void *,void *,ulong);
	void ccpLength(cocos2d::CCPoint const&);
	void ccArrayRemoveAllObjects(cocos2d::_ccArray *);
	void fseek64_file_func(void *, void *, unsigned long long, int);
	void ccCArrayRemoveAllValues(cocos2d::_ccCArray *);
	void ccArrayEnsureExtraCapacity(cocos2d::_ccArray	*,uint);
	void ccpRotateByAngle(cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
	void ccpRotateByAngle(cocos2d::CCPoint const&,cocos2d::CCPoint const&,float);
	void ccArrayAppendObjectWithResize(cocos2d::_ccArray *,cocos2d::CCObject *);
	void cc_utf8_trim_ws(std::vector<unsigned	short, std::allocator<unsigned short>> *);
	void CCRect,	bool (cocos2d::CCRect, cocos2d::CCRect));
	void CGAffineToGL(cocos2d::CCAffineTransform const*, float *);
	void ccArrayContainsObject(cocos2d::_ccArray *,cocos2d::CCObject *);
	void CCAffineTransformConcat(cocos2d::CCAffineTransform const&,cocos2d::CCAffineTransform	const&);
	void fopen64_file_func(void *,void	const*,int);
	void ccGLUseProgram(uint);
	void CCMessageBox(char const*, char const*);
	void ccArrayFree(cocos2d::_ccArray *&);
	void setValueForKey(char const*, char const*);
	void ccGLUseProgram(unsigned int);
	void ccpLerp(cocos2d::CCPoint const&,cocos2d::CCPoint const&,float);
	void ccCArrayInsertValueAtIndex(cocos2d::_ccCArray *,void	*,uint);
	void clampf(float, float,	float);
	void unz64local_getShort(cocos2d::zlib_filefunc64_32_def_s const*, void *, unsigned long *);
	void ccCArrayAppendValue(cocos2d::_ccCArray *,void *);
	void ccFileUtils_dictionaryWithContentsOfFileThreadSafe(char const*);
	void ccCArrayNew(unsigned	int);
	void __CCPointApplyAffineTransform(cocos2d::CCPoint const&, cocos2d::CCAffineTransform const&);
	void fill_fopen64_filefunc(cocos2d::zlib_filefunc64_def_s	*);
	void call_ztell64(cocos2d::zlib_filefunc64_32_def_s const*,void *);
	void unzOpenInternal(void	const*,cocos2d::zlib_filefunc64_32_def_s *,int);
	void ccCArrayContainsValue(cocos2d::_ccCArray *, void *);
	void __CCPointApplyAffineTransform(cocos2d::CCPoint const&,cocos2d::CCAffineTransform const&);
	void ccArrayAppendObject(cocos2d::_ccArray *,cocos2d::CCObject *);
	void CCPointFromString(char const*);
	void SetBlending(unsigned	int, unsigned int);
	void SetBlending(uint,uint);
	void valueForKey(char const*, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string>>> *);
	void generateUUID(void);
	void unzGetCurrentFileInfo(void *, cocos2d::unz_file_info_s *, char *, unsigned long, void *, unsigned long, char	*, unsigned long);
	void CCRect *>(false, false, std::random_access_iterator_tag);
	void CCAffineTransformInvert(cocos2d::CCAffineTransform const&);
	void ccpDistance(cocos2d::CCPoint	const&,cocos2d::CCPoint	const&);
	void ccpLineIntersect(cocos2d::CCPoint const&,cocos2d::CCPoint const&,cocos2d::CCPoint const&,cocos2d::CCPoint const&,float *,float *);
	void unzGetGlobalInfo(void *, cocos2d::unz_global_info_s *);
	void fclose_file_func(void *, void *);
	void ccGLDeleteTexture(unsigned int);
	void valueForKey(char const*,std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string	const,std::string>>> *);
	void ccCArrayRemoveValueAtIndex(cocos2d::_ccCArray *,uint);
	void fseek64_file_func(void *,void	*,ulong	long,int);
	void CCAffineTransformTranslate(cocos2d::CCAffineTransform const&, float,	float);
	void unz64local_getLong(cocos2d::zlib_filefunc64_32_def_s	const*,	void *,	unsigned long *);
	void fwrite_file_func(void	*,void *,void const*,ulong);
	void cc_utf8_trim_ws(std::vector<ushort,std::allocator<ushort>> *);
	void unzGoToFirstFile64(void *,cocos2d::unz_file_info64_s	*,char *,ulong);
	void unzOpenCurrentFile3(void *,int *,int	*,int,char const*);
	void CCRect, bool (cocos2d::CCRect, cocos2d::CCRect));
	void ccCArrayAppendValue(cocos2d::_ccCArray *, void *);
	void CCMessageBox(char const*,char const*);
	void ccGLEnableVertexAttribs(uint);
	void ccArrayAppendObjectWithResize(cocos2d::_ccArray *, cocos2d::CCObject	*);
	void CGAffineToGL(cocos2d::CCAffineTransform const*,float	*);
	void showPlatformDialog(char const*,char const*,char const*,char const*,cocos2d::DialogType);
	void ccArrayRemoveObjectAtIndex(cocos2d::_ccArray	*,uint,bool);
	void _base64Decode(uchar *,uint,uchar *,uint *);
	void unzGoToNextFile64(void *,cocos2d::unz_file_info64_s *,char *,ulong);
	void unz64local_getByte(cocos2d::zlib_filefunc64_32_def_s	const*,void *,int *);
	void call_zseek64(cocos2d::zlib_filefunc64_32_def_s const*, void *, unsigned long	long, int);
	void ccArrayNew(uint);
	void ccArrayRemoveObject(cocos2d::_ccArray *, cocos2d::CCObject *, bool);
	void CCRectFromString(char const*);
	void unzClose(void *);
	void ccGLBindTexture2D(uint);
	void setValueForKey(char const*,char const*);
	void FNTConfigLoadFile(char const*);
	void unzGetGlobalInfo(void *,cocos2d::unz_global_info_s *);
	void ferror_file_func(void *, void *);
	void unz64local_getLong64(cocos2d::zlib_filefunc64_32_def_s const*,void *,ulong long *);
	void unzReadCurrentFile(void *,void *,uint);
	void ferror_file_func(void *,void	*);
	void getXMLNodeForKey(char const*, _xmlNode **);
	void call_zopen64(cocos2d::zlib_filefunc64_32_def_s const*,void const*,int);
	void CCSizeFromString(char const*);
	void ccArrayEnsureExtraCapacity(cocos2d::_ccArray	*, unsigned int);
	void ccArrayDoubleCapacity(cocos2d::_ccArray *);
	void unz64local_GetCurrentFileInfoInternal(void *, cocos2d::unz_file_info64_s *, cocos2d::unz_file_info64_internal_s *, char *, unsigned long, void *, unsigned long, char *, unsigned long);
	void ccGLBindTexture2DN(uint,uint);
	void splitWithForm(char const*, std::vector<std::string, std::allocator<std::string>> &);
	void unzGoToNextFile64(void *, cocos2d::unz_file_info64_s	*, char	*, unsigned long);
	void _base64Decode(unsigned char *, unsigned int,	unsigned char *, unsigned int *);
	void ccpClamp(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&);
	void fwrite_file_func(void *, void *, void const*, unsigned long);
}
#endif