#ifndef MOF_EQUIPTRANSFORMATIONUI_H
#define MOF_EQUIPTRANSFORMATIONUI_H

class EquipTransformationUI{
public:
	void onMenuItemEquipClicked(cocos2d::CCObject *);
	void showStoneTips(int);
	void combiningItems(int);
	void MosaicFunctionOpen(int	*);
	void changeEquipmentMeuIcon(int);
	void setMentiongoodsShow(void);
	void onMenuItemPutOffStoneClicked(cocos2d::CCObject	*);
	void recv(int,int,char const*);
	void recv(int,void *);
	void setItemsEnable(int);
	void registerWithTouchDispatcher(void);
	void ccTouchMoved(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void setRisingStarShow(int,EquipInfo);
	void firstLoadEquip(void);
	void RefreshData(void);
	void Init(void);
	void getMaterialFromInI(int,int);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject	*,char const*);
	void decreaseLuckyStoneCount(void);
	void showEquipEffect(int, cocos2d::CCNode *, cocos2d::CCPoint);
	void init(void);
	void onMenuItemBlendIItemClicked(cocos2d::CCObject *);
	void setStrengthenShow(void);
	void setRisingStarShow(int,	EquipInfo);
	void setMentiongoodsDescNode(int);
	void ccTouchCancelled(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void onMenuItemBlendEquipClicked(cocos2d::CCObject *);
	void onMenuItemCombineClicked(cocos2d::CCObject *);
	void onMenuItemPutOffStoneClicked(cocos2d::CCObject *);
	void setBlendEquipInfor(int, EquipInfo);
	void onMenuItemEquipmentClicked(cocos2d::CCObject *);
	void showStrengthExpTip(int);
	void hideStoneTips(void);
	void recv(int,int,cocos2d::CCPoint,int);
	void onMenuItemTakeOffClicked(cocos2d::CCObject *);
	void getMaterialFromInI(int, int);
	void recv(int, int, char const*);
	void setProgressActionEnd(void);
	void showCombedEffect(void);
	void recv(int, int, cocos2d::CCPoint,	int);
	void onMenuItemCombiningItemClicked(cocos2d::CCObject *);
	void onEnter(void);
	void showEquipEffect(int,cocos2d::CCNode *,cocos2d::CCPoint);
	void showLuckyStoneInfo(void);
	void ccTouchMoved(cocos2d::CCTouch *,cocos2d::CCEvent	*);
	void setSelectItem(ItemGroup);
	void setEquipPreData(int, PlayerEquip *);
	void CombineFunctionOpen(int *);
	void EquipTransformationUI(void);
	void compareProps(ItemGroup,ItemGroup);
	void onExit(void);
	void onMenuItemStrengthenClicked(cocos2d::CCObject *);
	void setTipContent(std::string,prompttype,bool);
	void ccTouchEnded(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void recv(int, int,	char const*);
	void hideLuckyStoneInfo(void);
	void DeleteCombineSpr(void);
	void onMenuItemMentiongoodsClicked(cocos2d::CCObject *);
	void setMentiongoodsShow(int,EquipInfo);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void getLuckyStoneList(void);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *, char const*);
	void setFusionImageIsEnable(bool);
	void onMenuItemPropertyClicked(cocos2d::CCObject *);
	void onMenuItemCloseClicked(cocos2d::CCObject *);
	void showStrengthUpEffect(void);
	void setAttachShow(int,EquipInfo);
	void setMentiongoodsArrowShow(bool);
	void ccTouchMoved(cocos2d::CCTouch *,	cocos2d::CCEvent *);
	void ccTouchCancelled(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void onMenuItemLuckyStoneClicked(cocos2d::CCObject *);
	void setExpFull(void);
	void addEquipmentMeu(int);
	void ccTouchEnded(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void compareProps(ItemGroup, ItemGroup);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject	*, char	const*);
	void ~EquipTransformationUI();
	void recv(int, int,	cocos2d::CCPoint, int);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *,char const*);
	void ccTouchEnded(cocos2d::CCTouch *,	cocos2d::CCEvent *);
	void onMenuItemMentiongoodsDescClicked(cocos2d::CCObject *);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void setBlendEquipInfor(int,EquipInfo);
	void setMentiongoodsShow(int, EquipInfo);
	void setProgressRatio(bool);
	void setEquipPreData(int,PlayerEquip *);
	void cutTable(int);
	void DetectionFunctionOpen(void);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent	*);
	void recv(int, void	*);
	void setCombiningShow(void);
	void setTipContent(std::string, prompttype,	bool);
	void setAttachShow(int, EquipInfo);
	void ccTouchMoved(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void setPageSpritePostion(int);
	void selectLuckyStoneEffect(void);
	void setMosaicShow(void);
	void onMenuItemMosaicItemClicked(cocos2d::CCObject *);
	void recv(int, void *);
	void onMenuItemMentiongoodsClicked(cocos2d::CCObject	*);
	void blendEquipFunctionOpen(int *);
	void comfirmFusionEquip(void);
	void create(void);
	void ccTouchBegan(cocos2d::CCTouch *,	cocos2d::CCEvent *);
	void ccTouchEnded(cocos2d::CCTouch *,cocos2d::CCEvent	*);
	void setBlendEquipShow(void);
	void onMenuItemCombineAllClicked(cocos2d::CCObject *);
	void cancelFusionEquip(void);
}
#endif