#ifndef MOF_GAME_H
#define MOF_GAME_H

class Game{
public:
	void setPetAiType(int);
	void update(float);
	void nextArea(void);
	void getHeight(void);
	void getWidth(void);
	void getState(void);
	void getClickNPCid(void);
	void registerWithTouchDispatcher(void);
	void updateObjOrder(float);
	void getFashTimerCount(void)const;
	void setFightModel(FightModel);
	void getCameraControlObjPoint(void);
	void createContent(cocos2d::CCScene *);
	void enterScene(int,cocos2d::CCPoint);
	void startRecordNetworkStuck(float);
	void mainRoleIsInTown(void);
	void stopCutScene(void);
	void init(void);
	void setMsgType(int);
	void getIsReadyToNextArea(void);
	void getFightModel(void);
	void setClickNPCid(int);
	void copyBackToTown(void);
	void getIsFindingPath(void);
	void getClickPortalID(void)const;
	void ccTouchEnded(cocos2d::CCTouch *, cocos2d::CCEvent	*);
	void perSecTimer(float);
	void setIsFindingPath(bool);
	void slowDown(float,float);
	void slowDown(float,	float);
	void clearGameData(void);
	void chgState(GameState);
	void getIsFirstNotifyPetProp(void);
	void setState(GameState);
	void setAutoBatIsOPen(bool);
	void updateView(float);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent	*);
	void getClickPortalID(void);
	void showError(int);
	void enterScene(int,	cocos2d::CCPoint);
	void onExit(void);
	void getCameraControlObj(void);
	void getIsPassiveskill(void);
	void ccTouchEnded(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void addMarkDeleteObj(GameObject *);
	void playKOEffect(void);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void setIsFirstInDungeon(bool);
	void getDailyQuestRefreshTimes(void)const;
	void setIsReadyToNextArea(bool);
	void roleBagIsEmpty(void);
	void getPetAiType(void);
	void startFashionSchedule(void);
	void readyToNextArea(void);
	void setFashTimerCount(int);
	void createUI(void);
	void getClickNPCid(void)const;
	void endRecordNetworkStuck(void);
	void checkOpenPortal(int, int);
	void getMsgType(void)const;
	void recordNetworkStuckTimeUp(float);
	void setClickPortalID(int);
	void getMainRoleSceneType(void);
	void draw(void);
	void ccTouchEnded(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void slowDownEnd(float);
	void onEnterTransitionDidFinish(void);
	void setIsPassiveskill(bool);
	void Game(void);
	void readyOk(float);
	void ~Game();
	void setIsFirstNotifyPetProp(bool);
	void setDailyQuestRefreshTimes(int);
	void getFashTimerCount(void);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void startPerSecTimer(void);
	void passLevel(void);
	void leaveScene(Scene *);
	void getDailyQuestRefreshTimes(void);
	void deleteMarkedObjs(void);
	void bornView(void);
	void checkOpenPortal(int,int);
	void getIsFirstInDungeon(void);
	void getMsgType(void);
	void getBattlePropSacleUp(void);
	void setBattlePropSacleUp(bool);
	void freshfashionUsingTimer(float);
	void stopPerSecTimer(void);
	void createMainRole(void);
	void setLastTownId(int);
	void getAutoBatIsOPen(void);
}
#endif