#ifndef MOF_MAINUI_H
#define MOF_MAINUI_H

class MainUI{
public:
	void setLevel(void);
	void onMenuItemPathFindingClicked(cocos2d::CCObject	*);
	void onNewEquipTipsClicked(cocos2d::CCObject *);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *,char	const*);
	void onResolveCCBCCControlSelector(cocos2d::CCObject	*, char	const*);
	void onResolveCCBCCControlSelector(cocos2d::CCObject	*,char const*);
	void showNewEquipTips(bool);
	void changeOtherAndSearchRoleState(int);
	void onMenuItemGoldClicked(cocos2d::CCObject *);
	void setFighting(void);
	void onMenuItemFriendListClicked(cocos2d::CCObject	*);
	void editBoxTextChanged(cocos2d::extension::CCEditBox *, std::string	const&);
	void setAddFriendTipsHide(void);
	void addFriendTips(void);
	void setEnergyValue(void);
	void onMenuItemCheeckRoleInforClicked(cocos2d::CCObject *);
	void addNewMailAction(void);
	void confirmAddFriends(void);
	void OnMenuItemEquipPetclicked(cocos2d::CCObject *);
	void setPathingArrowShow(void);
	void recv(int, int, cocos2d::CCPoint, int);
	void editBoxEditingDidBegin(cocos2d::extension::CCEditBox *);
	void onAssignCCBMemberVariable(cocos2d::CCObject *,char const*,cocos2d::CCNode *);
	void onMenuItemTransformClicked(cocos2d::CCObject *);
	void onMenuItemTreasureClicked(cocos2d::CCObject *);
	void addAFriend(int);
	void onMenuItemAddToFriendClicked(cocos2d::CCObject *);
	void onAssignCCBMemberVariable(cocos2d::CCObject *, char const*, cocos2d::CCNode *);
	void Init(void);
	void editBoxTextChanged(cocos2d::extension::CCEditBox *, std::string const&);
	void onMenuItemHPClicked(cocos2d::CCObject *);
	void onMenuItemAddEnergyClicked(cocos2d::CCObject *);
	void MainUI(void);
	void setOpenImageShow(void);
	void setChatingImageIsShow(bool);
	void onMenuItemShopingClicked(cocos2d::CCObject *);
	void setSearchEditShow(bool);
	void onMenuItemGuildClicked(cocos2d::CCObject *);
	void onMenuItemAwardClicked(cocos2d::CCObject *);
	void setPetAILabelShow(void);
	void onMenuItemAddToFriendClicked(cocos2d::CCObject	*);
	void showCanSkillEffect(bool);
	void setVipLevel(void);
	void setFriendsNodeShow(bool, bool);
	void recv(int, int, char const*);
	void insertMapValue(std::string,cocos2d::CCMenuItemImage *);
	void onMenuItemFriendListClicked(cocos2d::CCObject *);
	void ~MainUI();
	void setAllMenuPriority(void);
	void deleteNewMailAction(void);
	void addHelperNoticeEffect(std::string, int);
	void onMenuItemGuildApplyTipsClose(void);
	void recv(int,int,char const*);
	void onMenuItemAddFriendTipsClicked(cocos2d::CCObject *);
	void onMenuItemChatingClicked(cocos2d::CCObject *);
	void recv(int,int,cocos2d::CCPoint,int);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *,char const*);
	void GetJoyStickPointer(void);
	void addChartContent(charting);
	void onMenuItemSortClicked(cocos2d::CCObject *);
	void onMenuItemVipClicked(cocos2d::CCObject *);
	void removeFriendsOnlinecallback(cocos2d::CCLabelTTF *);
	void setExpValue(void);
	void setPosition(cocos2d::CCPoint const&);
	void cancelAddFriends(void);
	void editBoxTextChanged(cocos2d::extension::CCEditBox *,std::string const&);
	void onMenuItemSettingClicked(cocos2d::CCObject *);
	void onMenuItemPetClicked(cocos2d::CCObject *);
	void onMenuItemAddressClicked(cocos2d::CCObject *);
	void onMenuItementertainmentClicked(cocos2d::CCObject *);
	void onEnter(void);
	void setRoleTableViewShow(int);
	void setChargeIconHide(void);
	void onMenuItemMonthCardClicked(cocos2d::CCObject *);
	void onMenuItemHandClicked(cocos2d::CCObject *);
	void onMenuItemChannelClicked(cocos2d::CCObject *);
	void addASceneRole(int);
	void setTaskpathfindingIcon(int,int,eClientQuestState);
	void getSortUiIcon(void);
	void onMenuItemHelperClicked(cocos2d::CCObject *);
	void init(void);
	void addSearchFriend(int);
	void setRMB(void);
	void onMenuItemQueenBlessingClicked(cocos2d::CCObject *);
	void setAddFriendTipShow(bool,bool);
	void tableViewMove(void);
	void checkFindPathIcon(void);
	void deleteLightingEffect(std::string);
	void addLightingEffect(std::string);
	void duelApplyTips(void);
	void onMenuItemMailClicked(cocos2d::CCObject *);
	void onMenuItemAutoClicked(cocos2d::CCObject *);
	void getOpenImagesByString(std::string);
	void onMenuItemChangePetAIClicked(cocos2d::CCObject	*);
	void showCanPetCollectEffect(bool);
	void onMenuItemTaskClicked(cocos2d::CCObject *);
	void onMenuItemConfirmSearchClicked(cocos2d::CCObject *);
	void onMenuItemActiveClicked(cocos2d::CCObject *);
	void setTaskpathfindingIcon(int, int, eClientQuestState);
	void showFriendsOnlineTips(int);
	void sortOpenImagePos(void);
	void onMenuItemFriendClicked(cocos2d::CCObject *);
	void onMenuItemChargeActClicked(cocos2d::CCObject *);
	void onControlFunctionofOpenClicked(cocos2d::CCObject *, unsigned int);
	void onMenuItemChangePetAIClicked(cocos2d::CCObject *);
	void onMenuItemPathFindingClicked(cocos2d::CCObject *);
	void onMenuItemPetCollectClicked(cocos2d::CCObject *);
	void onMenuItemMakeDuleTipsClicked(cocos2d::CCObject *);
	void onShowActionEnd(cocos2d::CCNode *);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void addHelperNoticeEffect(std::string,int);
	void onMenuItemVipBagClicked(cocos2d::CCObject *);
	void InitOpenImage(void);
	void changeFriendOnline(int);
	void onMenuItemPeopleClicked(cocos2d::CCObject *);
	void getNoSortOpenImageMap(void);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *, char const*);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *, char const*);
	void onMenuItemSearchFriendClicked(cocos2d::CCObject *);
	void editBoxEditingDidEnd(cocos2d::extension::CCEditBox *);
	void onMenuItemGuildApplyTipsClicked(cocos2d::CCObject *);
	void onMenuItemChartClicked(cocos2d::CCObject *);
	void changeFriendRoleState(int);
	void setFriendsNodeShow(bool,bool);
	void onMenuItemStarUPClicked(cocos2d::CCObject *);
	void onMenuItemCancelSearchClicked(cocos2d::CCObject *);
	void insertMapValue(std::string, cocos2d::CCMenuItemImage *);
	void onMenuItemHPClicked(cocos2d::CCObject	*);
	void onMenuItemPetCollectClicked(cocos2d::CCObject	*);
	void onMenuItemSkillClicked(cocos2d::CCObject *);
	void editBoxReturn(cocos2d::extension::CCEditBox *);
	void onMenuItemNearFriendClicked(cocos2d::CCObject	*);
	void guildApplyTips(void);
	void ccTouchBegan(cocos2d::CCTouch	*, cocos2d::CCEvent *);
	void onControlFunctionofOpenClicked(cocos2d::CCObject *,uint);
	void recv(int,void *);
	void showMyFriendsNum(void);
	void onMenuItemFamousHallClicked(cocos2d::CCObject	*);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *,char const*);
	void setLimitAwardPos(void);
	void ccTouchBegan(cocos2d::CCTouch	*,cocos2d::CCEvent *);
	void deleteMyFriend(void);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void recv(int, void *);
	void onMenuItemPetClicked(cocos2d::CCObject	*);
	void onMenuItemFamousHallClicked(cocos2d::CCObject *);
	void onMenuItemMakeDuleClicked(cocos2d::CCObject *);
	void showDialogOnImageClicked(std::string);
	void onMenuItemDailytaskClicked(cocos2d::CCObject *);
	void showBattlePetInfor(void);
	void onMenuItemAutoTestClicked(cocos2d::CCObject *);
	void recv(int,void	*);
	void onMenuItemPetHeadClicked(cocos2d::CCObject *);
	void getOpenImageList(void);
	void onMenuItemNearFriendClicked(cocos2d::CCObject *);
	void onMenuItemCloseTipsClicked(cocos2d::CCObject *);
	void setGold(void);
	void setOpenImageShowByTask(void);
	void onMenuItemMysticShopClicked(cocos2d::CCObject *);
	void onMenuItemVipClicked(cocos2d::CCObject	*);
	void showCanStarEffect(bool);
	void onMenuItemChargeClicked(cocos2d::CCObject *);
	void create(void);
	void addDataToFrienfsTipslist(int);
	void resetLightingEffect(void);
	void onExit(void);
	void onMenuItemMysticShopClicked(cocos2d::CCObject	*);
	void onMenuItemTotemClicked(cocos2d::CCObject *);
	void setCityLine(void);
}
#endif