#ifndef MOF_PETMONSTERUI_H
#define MOF_PETMONSTERUI_H

class PetMonsterUI{
public:
	void hideAbsorted(void);
	void deletePetNameAndAddPro(cocos2d::CCNode *, int);
	void onMenuItemGoToFightingClicked(cocos2d::CCObject	*);
	void showCheersTitleLabel(cocos2d::CCNode *,	int);
	void createChooseMainPetEffect(void);
	void sortAbsortedsPets(void);
	void absortPet(int, int);
	void onMenuItemChooseMainPetClicked(cocos2d::CCObject *);
	void setLearnFinshSkillTips(int);
	void detectionSkillCanUpdata(PetMonster *,int);
	void absortPet(int,int);
	void onResolveCCBCCControlSelector(cocos2d::CCObject	*,char const*);
	void PetMonsterUI(void);
	void onMenuItemCloseUpdateSkillsClicked(cocos2d::CCObject *);
	void absortedPetStep2(void);
	void sortBeAbsortedPets(void);
	void getAllExp(PetMonster *);
	void changePetMonsterTitle(TitleType);
	void canMergePet(int, int);
	void createBeabsortedPet(PetMonster *, int);
	void onMenuItemChoosePet4UpStepClicked(cocos2d::CCObject *);
	void showCheersTitleLabel(cocos2d::CCNode *,int);
	void createBeabsortedPetEffect(int);
	void initChoosePetViewDatas(bool);
	void isShowNegativeModel4UpStep(bool,PetMonster *);
	void isShowMainPetModel4UpStep(bool,	PetMonster *);
	void addCheersPet(int, int);
	void showOpenLevel(cocos2d::CCNode *, int);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *,char	const*);
	void onMenuItemCheerPetsClicked(cocos2d::CCObject *);
	void onMenuItemOpenIntroduceClicked(cocos2d::CCObject	*);
	void getUpdateGrowthItems(void);
	void onMenuItemUpdateSkillsClicked(cocos2d::CCObject *);
	void onMenuItemChooseMainPetClicked(cocos2d::CCObject	*);
	void updateGrowthByServerBack(int);
	void absortedPetStep1(void);
	void clilckUpdateGrowth(void);
	void showPetNameAndAddPro(cocos2d::CCNode *,	int, PetMonster	*);
	void checkSkillHasArriveMaxLvl(int,PetMonster *);
	void canMergePet(int,int);
	void clearAllSwallowData(void);
	void showPetUpStar(int);
	void setSkillLvlShow(int,int);
	void deleteCheersPet(int);
	void showSwallowAttribute(std::vector<PetMonster *,std::allocator<PetMonster	*>>);
	void getPetQualityStr(QualityColor);
	void calculateAddtionAttri(std::vector<PetMonster *,std::allocator<PetMonster *>>);
	void showSecondaryPetInfo(PetMonster	*);
	void init(void);
	void setNoLearnSkillTips(int);
	void deletBeabsortedPet(int);
	void isShowMainPetModel(bool, PetMonster *);
	void showMerge4UpStep(void);
	void setArrowSprIsMove(bool,int);
	void getProByPos(int,PetMonster *,int *);
	void isShowMainPetModel(bool,PetMonster *);
	void reqMergerPet(void);
	void createSkillControlButton(int,cocos2d::CCPoint);
	void hideStarUpDescNode(void);
	void showPetNameAndAddPro(cocos2d::CCNode *,int,PetMonster *);
	void initCheersPetDatas(int);
	void calculateRateAddtionAttri(std::vector<PetMonster *, std::allocator<PetMonster *>>);
	void absortedPetStep4(void);
	void showPetAbsorted(void);
	void InitControl(void);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *,char const*);
	void setUpStepEffect(void);
	void showStrDescNode(void);
	void setGoToFightingImageState(bool);
	void setUpdateGrowthDesc(bool);
	void updateSkillsInforByServerBack(int, int);
	void onMenuItemPetEatingClicked(cocos2d::CCObject *);
	void reqUpdateGrowth(void);
	void setattributeImageIsEnable(bool);
	void calculateAbsortLvl(std::vector<PetMonster *, std::allocator<PetMonster *>>);
	void clearAllSwallowData4UpStep(void);
	void changePetAddPro(int, int);
	void onMenuItemCloseUpdateGrowthClicked(cocos2d::CCObject *);
	void setArrowSprIsMove(bool,	int);
	void onEnter(void);
	void setMainPetImageIsEnabled(bool);
	void setPetSkillIcon(PetMonster *);
	void getProByPos(int, PetMonster *, int *);
	void checkSkillHasArriveMaxLvl(int, PetMonster *);
	void onResolveCCBCCControlSelector(cocos2d::CCObject *, char const*);
	void growthIsArriveMaxValue(void);
	void addCheersPet(int,int);
	void onMenuItemUpdateGrowthClicked(cocos2d::CCObject *);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent	*);
	void sortabsortedPet(void);
	void hideStrDescNode(void);
	void onMenuItemCloseClicked(cocos2d::CCObject	*);
	void onControlStarUpDescClicked(cocos2d::CCObject *,uint);
	void absortedPetStep3(void);
	void onExit(void);
	void onMenuItemCloseRuleClicked(cocos2d::CCObject *);
	void getSkillBooksNumByQua(int,bool,int);
	void showPetModel(PetMonster	*, cocos2d::CCNode *);
	void createchooseBeEatPetEffect(void);
	void isShowNegativeModel4UpStep(bool, PetMonster *);
	void createSkillControlButton(int, cocos2d::CCPoint);
	void sortAbsortedsPets4UpStep(void);
	void closeUpdateGrowthTips(void);
	void getSkillBooksNumByQua(int, bool, int);
	void refreshPet(PetMonster *);
	void setHasLearnSkillTips(int);
	void onMenuItemPetCheersClicked(cocos2d::CCObject *);
	void showOpenLevel(cocos2d::CCNode *,int);
	void setSkillLvlShow(int, int);
	void showPetModel(PetMonster	*,cocos2d::CCNode *);
	void showPetMonsterHeadBg(cocos2d::CCNode *);
	void registerWithTouchDispatcher(void);
	void setBeabsortedPetIsEnabeled(bool);
	void onMenuItemOpenIntroduceClicked(cocos2d::CCObject *);
	void getSkillPosByTemplate(int);
	void ccTouchBegan(cocos2d::CCTouch *, cocos2d::CCEvent *);
	void checkAbsortedPetAttriIsGetMax(void);
	void onMenuItemUpdateGrowthClicked(cocos2d::CCObject	*);
	void reqAbsorbPet(void);
	void onControlStrDescClicked(cocos2d::CCObject *, unsigned int);
	void setSkillTipsDesc(SkillCfgDef *,SkillTisData,bool);
	void unActivePet(int);
	void initCheersPetNode(void);
	void createchooseMainEatOwnPetEffect(void);
	void calculateRateAddtionAttri(std::vector<PetMonster *,std::allocator<PetMonster *>>);
	void onMenuItemBeEatedClicked(cocos2d::CCObject *);
	void showStarUpDescNode(void);
	void setMainPetInfor(PetMonster *);
	void showPetUpLevel(void);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *, char const*);
	void playCheersLabelEffect(cocos2d::CCNode *);
	void showPetUpLevel4UpStep(void);
	void onMenuItemPetSwallowClicked(cocos2d::CCObject *);
	void onMenuItemChooseMainPet4UpStepClicked(cocos2d::CCObject *);
	void createOrChangeStarNode(cocos2d::CCNode *,PetMonster *,cocos2d::CCPoint);
	void hideBeEatInfo(void);
	void initChoosePetViewDatas4UpStep(bool);
	void onMenuItemCloseClicked(cocos2d::CCObject *);
	void onMenuItemStartUpdateGrowthClicked(cocos2d::CCObject *);
	void setSkillDesc(int,cocos2d::CCPoint);
	void setPetDetailsUI(PetMonster *);
	void calculateExp(std::vector<PetMonster *,std::allocator<PetMonster	*>>);
	void hideUpStepEffect(void);
	void setSwallowAttributeHide(void);
	void onMenuItemShowUpdateSKillClicked(cocos2d::CCObject *);
	void setCloseImageIsEnable(bool);
	void OnMenuItemEatOwnClicked(cocos2d::CCObject *);
	void setSkillDesc(int, cocos2d::CCPoint);
	void setMainPetInfor4UpStep(PetMonster *);
	void setMainpetInfoHide4UpStep(void);
	void ~PetMonsterUI();
	void changePetAddPro(int,int);
	void showSwallowAttribute(std::vector<PetMonster *, std::allocator<PetMonster *>>);
	void create(void);
	void BeabsortedPetQuaiSHightMainPet(std::vector<PetMonster *, std::allocator<PetMonster *>>);
	void deletePetNameAndAddPro(cocos2d::CCNode *,int);
	void onControlStrDescClicked(cocos2d::CCObject *,uint);
	void refreshUpdataSkillTips(int);
	void onResolveCCBCCControlSelector(cocos2d::CCObject	*, char	const*);
	void onMenuItemUpdateSkillsClicked(cocos2d::CCObject	*);
	void sortBeAbsortedPets4UpStep(void);
	void onMenuItemGoToSwallowClicked(cocos2d::CCObject *);
	void createOrChangeStarNode(cocos2d::CCNode *, PetMonster *,	cocos2d::CCPoint);
	void ccTouchBegan(cocos2d::CCTouch *,cocos2d::CCEvent *);
	void onMenuItemGoToFightingClicked(cocos2d::CCObject *);
	void calculateAbsortLvl(std::vector<PetMonster *,std::allocator<PetMonster *>>);
	void activePet(int);
	void onMenuItemPetPropertyClicked(cocos2d::CCObject *);
	void setBeEatPetImageIsEnabled(bool);
	void calculateUpStarProbability(PetMonster *,std::vector<PetMonster *,std::allocator<PetMonster *>>);
	void setSeletedPet(PetMonster *);
	void setSkillTipsDesc(SkillCfgDef *,	SkillTisData, bool);
	void calculateUpStarProbability(PetMonster *, std::vector<PetMonster	*, std::allocator<PetMonster *>>);
	void showCheersPetDesc(void);
	void updateSkillsInforByServerBack(int,int);
	void onResolveCCBCCMenuItemSelector(cocos2d::CCObject *,char const*);
	void calculateAddtionAttri(std::vector<PetMonster *,	std::allocator<PetMonster *>>);
	void onMenuItemUpStepClicked(cocos2d::CCObject *);
	void onMenuItemChooseMainPet4UpStepClicked(cocos2d::CCObject	*);
	void onControlStarUpDescClicked(cocos2d::CCObject *,	unsigned int);
	void setMainPetInforNodeHide(void);
	void BeabsortedPetQuaiSHightMainPet(std::vector<PetMonster *,std::allocator<PetMonster *>>);
	void calculateExp(std::vector<PetMonster *, std::allocator<PetMonster *>>);
	void isShowMainPetModel4UpStep(bool,PetMonster *);
	void createBeabsortedPet(PetMonster *,int);
	void showDetailOrAbsort(TitleType);
	void detectionSkillCanUpdata(PetMonster *, int);
	void setMainEatPetImageIsEnabled(bool);
	void onMenuItemChooseBeabsortedPetClicked(cocos2d::CCObject *);
	void setShowSkillsList(PetMonster *);
	void showGoldNode(void);
	void initSkillTips(void);
}
#endif