#ifndef MOF_RANDOM_ACCESS_ITERATOR_TAG>_H
#define MOF_RANDOM_ACCESS_ITERATOR_TAG>_H

class random_access_iterator_tag>{
public:
	void __copy_b<UpdatePackageDef *, UpdatePackageDef *>(false,	false, std::random_access_iterator_tag);
	void copy<petListData *,petListData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<MDMemoryDescriptor *,MDMemoryDescriptor *>(false,false,std::random_access_iterator_tag). PRESS KEYPAD CTRL-"+" TO EXPAND];
	void copy<PetEliteInfor *, PetEliteInfor *>(false, false, std::random_access_iterator_tag);
	void __copy_b<GuildShopData *, GuildShopData	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<chatingContent	*, chatingContent *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_pvp_log *,obj_pvp_log *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_roleinfo *, obj_roleinfo *>(false,	false, std::random_access_iterator_tag);
	void copy<obj_skill_effect_info const*,obj_skill_effect_info*>(false,false,std::random_access_iterator_tag);
	void __copy_b<SkillHurt *, SkillHurt	*>(false, false, std::random_access_iterator_tag);
	void copy<monsterWave *,monsterWave *>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildBossLvlDef	*,GuildBossLvlDef *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_copyaward *,obj_copyaward *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_copy_resettimes *,obj_copy_resettimes *>(false,false,std::random_access_iterator_tag);
	void copy<petListData	*, petListData *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_skill_effect_info *,obj_skill_effect_info *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasure_scene *,obj_treasure_scene	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_beAttacked	*, obj_beAttacked *>(false, false, std::random_access_iterator_tag);
	void copy<obj_skill_effect_info *, obj_skill_effect_info *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_chat *,obj_guild_chat	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_friendDunge_record	*, obj_friendDunge_record *>(false, false, std::random_access_iterator_tag);
	void copy<obj_pvp_role *, obj_pvp_role *>(false, false, std::random_access_iterator_tag);
	void __copy_b<SysTotemGroupTotem *,SysTotemGroupTotem	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_pvp_role *,obj_pvp_role *>(false,false,std::random_access_iterator_tag);
	void copy<obj_skill_effect_info const*, obj_skill_effect_info*>(false, false,	std::random_access_iterator_tag);
	void __copy_b<MailData *, MailData *>(false,	false, std::random_access_iterator_tag);
	void copy<ItemGroup const*,ItemGroup*>(false,false,std::random_access_iterator_tag);
	void __copy_b<TimeLimitKillCopyAward	*, TimeLimitKillCopyAward *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_pos_info *, obj_pos_info *>(false,	false, std::random_access_iterator_tag);
	void copy<TreasureFightRoomInfo const*,TreasureFightRoomInfo*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_beSkilled *,obj_beSkilled *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_updateEquip *, obj_updateEquip *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_questProgress *, obj_questProgress	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<PetEliteInfor *, PetEliteInfor	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_addordelItem *,obj_addordelItem *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_beSkilled *, obj_beSkilled	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<CasinoPet *, CasinoPet	*>(false, false, std::random_access_iterator_tag);
	void copy<obj_mysticalmonster const*,obj_mysticalmonster*>(false,false,std::random_access_iterator_tag);
	void copy<obj_lotteryhistory *,obj_lotteryhistory *>(false,false,std::random_access_iterator_tag);
	void __copy_b<void (false, false, std::random_access_iterator_tag);
	void __copy_b<obj_role *, obj_role *>(false,	false, std::random_access_iterator_tag);
	void copy<PetEliteInfor *,PetEliteInfor *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_tlk_monster *, obj_tlk_monster *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_item *, obj_item *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<PetList	*,PetList *>(false,false,std::random_access_iterator_tag);
	void copy<TreasureGuildResult *,TreasureGuildResult *>(false,false,std::random_access_iterator_tag);
	void __copy_b<Dialog	*, Dialog *>(false, false, std::random_access_iterator_tag);
	void __copy_b<QueenBlessTimeItem *, QueenBlessTimeItem *>(false, false, std::random_access_iterator_tag);
	void copy<RoleEquipSkill *, RoleEquipSkill *>(false, false, std::random_access_iterator_tag);
	void __copy_b<GuildSkillProperty *,GuildSkillProperty	*>(false,false,std::random_access_iterator_tag);
	void copy<TreasureFightRoomInfo const*, TreasureFightRoomInfo*>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_mail *,obj_mail *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_mail *, obj_mail *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_Petpaihangdata *,obj_Petpaihangdata	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_guild_info	*, obj_guild_info *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_worldfly_info *,obj_worldfly_info *>(false,false,std::random_access_iterator_tag);
	void copy<obj_tlk_monster *,obj_tlk_monster *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_guild_log_info *,obj_guild_log_info	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<TreasureManorData *,TreasureManorData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<FashionData *,	FashionData *>(false, false, std::random_access_iterator_tag);
	void copy<RoleEquipSkill const*,RoleEquipSkill*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_roleinfo *,obj_roleinfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_honorCondInfo *, obj_honorCondInfo	*>(false, false, std::random_access_iterator_tag);
	void copy<ItemGroup const*, ItemGroup*>(false, false,	std::random_access_iterator_tag);
	void __copy_b<MDMemoryDescriptor *,MDMemoryDescriptor	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<TreasureGuildResult *,TreasureGuildResult *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_paihangdata *, obj_paihangdata *>(false, false, std::random_access_iterator_tag);
	void __copy_b<ItemGroup *,ItemGroup *>(false,false,std::random_access_iterator_tag);
	void __copy_b<totemList *,totemList *>(false,false,std::random_access_iterator_tag);
	void __copy_b<TreasureManorData *, TreasureManorData	*>(false, false, std::random_access_iterator_tag);
	void copy<Monster **,	LivingObject **>(false,	false, std::random_access_iterator_tag);
	void copy<QueenBlessing const*, QueenBlessing*>(false, false,	std::random_access_iterator_tag);
	void __copy_b<LotteryItemData *, LotteryItemData *>(false, false, std::random_access_iterator_tag);
	void __copy_b<petListData *,	petListData *>(false, false, std::random_access_iterator_tag);
	void __copy_b<ScoreItem *, ScoreItem	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_tlk_monster	*,obj_tlk_monster *>(false,false,std::random_access_iterator_tag);
	void __copy_b<MDMemoryDescriptor *, MDMemoryDescriptor *>(false, false, std::random_access_iterator_tag);
	void __copy_b<IconAwardDef *, IconAwardDef *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_rankdata *, obj_treasurecopy_rankdata	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_mysticalcopy *,obj_mysticalcopy *>(false,false,std::random_access_iterator_tag);
	void __copy_b<MatchResult *,	MatchResult *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_capsuletoy_info *,obj_capsuletoy_info *>(false,false,std::random_access_iterator_tag);
	void __copy_b<MysteriousInfo	*, MysteriousInfo *>(false, false, std::random_access_iterator_tag);
	void __copy_b<QueenBlessTimeItem *,QueenBlessTimeItem	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_honorInfo *, obj_honorInfo	*>(false, false, std::random_access_iterator_tag);
	void copy<IllustrationsState const*,IllustrationsState*>(false,false,std::random_access_iterator_tag);
	void __copy_b<MatchResult *,MatchResult *>(false,false,std::random_access_iterator_tag);
	void __copy_b<TreasureGuildResult *,	TreasureGuildResult *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_private_chat *,obj_private_chat *>(false,false,std::random_access_iterator_tag);
	void copy<GuildShopData *, GuildShopData *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_dungeawawrd *, obj_dungeawawrd *>(false, false, std::random_access_iterator_tag);
	void copy<teamInfor *, teamInfor *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_constelldata *,obj_constelldata *>(false,false,std::random_access_iterator_tag);
	void __copy_b<petListData *,petListData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_constelldata *, obj_constelldata *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<RankData *, RankData *>(false,	false, std::random_access_iterator_tag);
	void copy<FashionData	const*,	FashionData*>(false, false, std::random_access_iterator_tag);
	void __copy_b<RoleEquipSkill	*, RoleEquipSkill *>(false, false, std::random_access_iterator_tag);
	void copy<IllustrationsState *,IllustrationsState *>(false,false,std::random_access_iterator_tag);
	void __copy_b<MatElement *,MatElement	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<TlkMonsterCfgDef *, TlkMonsterCfgDef *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<LotteryItemData	*,LotteryItemData *>(false,false,std::random_access_iterator_tag);
	void copy<Server const*, Server*>(false, false, std::random_access_iterator_tag);
	void __copy_b<IllustraData *, IllustraData *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<Server	*, Server *>(false, false, std::random_access_iterator_tag);
	void copy<FashionData *,FashionData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_totem_info *,obj_totem_info	*>(false,false,std::random_access_iterator_tag);
	void copy<obj_honorInfo const*, obj_honorInfo*>(false, false,	std::random_access_iterator_tag);
	void copy<Server *,Server *>(false,false,std::random_access_iterator_tag);
	void copy<obj_tlk_monster const*,obj_tlk_monster*>(false,false,std::random_access_iterator_tag);
	void copy<obj_roleinfo *, obj_roleinfo *>(false, false, std::random_access_iterator_tag);
	void copy<MysteriousInfo *, MysteriousInfo *>(false, false, std::random_access_iterator_tag);
	void copy<TimeLimitKillCopyAward const*, TimeLimitKillCopyAward*>(false, false, std::random_access_iterator_tag);
	void copy<teamInfor *,teamInfor *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_copy_resettimes *,	obj_copy_resettimes *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_questProgress *,obj_questProgress *>(false,false,std::random_access_iterator_tag);
	void copy<obj_petBattleProp const*, obj_petBattleProp*>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_private_chat *, obj_private_chat *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<GuildApplyData *,GuildApplyData	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<IconAwardDef *,IconAwardDef *>(false,false,std::random_access_iterator_tag);
	void copy<obj_copy_resettimes *,obj_copy_resettimes *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_worldrole_info *, obj_worldrole_info *>(false, false, std::random_access_iterator_tag);
	void copy<obj_mysticalmonster	*, obj_mysticalmonster *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<QualityColor *, QualityColor *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_recharge_info *, obj_recharge_info	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_monster_average_hurt *, obj_monster_average_hurt *>(false,	false, std::random_access_iterator_tag);
	void copy<teamInfor const*,teamInfor*>(false,false,std::random_access_iterator_tag);
	void __copy_b<totemList *, totemList	*>(false, false, std::random_access_iterator_tag);
	void copy<GuildMemberData *,GuildMemberData *>(false,false,std::random_access_iterator_tag);
	void copy<obj_guild_skill *, obj_guild_skill *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_store_goods_info *, obj_store_goods_info *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<addValueDesc *, addValueDesc *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_attackedTarget *,obj_attackedTarget	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<QualityColor *,QualityColor *>(false,false,std::random_access_iterator_tag);
	void copy<RoleEquipSkill const*, RoleEquipSkill*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_info *,obj_guild_info	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildNewsData *, GuildNewsData	*>(false, false, std::random_access_iterator_tag);
	void copy<addValueDesc const*, addValueDesc*>(false, false, std::random_access_iterator_tag);
	void copy<QueenBlessing const*,QueenBlessing*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_guild_skill *, obj_guild_skill *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_chat	*, obj_guild_chat *>(false, false, std::random_access_iterator_tag);
	void copy<TlkMonsterCfgDef *,	TlkMonsterCfgDef *>(false, false, std::random_access_iterator_tag);
	void __copy_b<ScoreItem *,ScoreItem *>(false,false,std::random_access_iterator_tag);
	void __copy_b<PetChooseData *,PetChooseData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<chatingContent *,chatingContent	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_role *,obj_role *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_hurts *, obj_hurts	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<GuildMemberData	*,GuildMemberData *>(false,false,std::random_access_iterator_tag);
	void copy<teamInfor const*, teamInfor*>(false, false,	std::random_access_iterator_tag);
	void __copy_b<TreasureScoreData *,TreasureScoreData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<LuckystoneListData *, LuckystoneListData *>(false, false, std::random_access_iterator_tag);
	void __copy_b<TimeLimitKillCopyAward *,TimeLimitKillCopyAward	*>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_log	*, obj_pvp_log *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<teamInfor *, teamInfor	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_member *, obj_guild_member *>(false,	false, std::random_access_iterator_tag);
	void copy<IllustrationsState *, IllustrationsState *>(false, false, std::random_access_iterator_tag);
	void __copy_b<Server *,Server	*>(false,false,std::random_access_iterator_tag);
	void copy<obj_copy_resettimes	*, obj_copy_resettimes *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_pvp_log *,	obj_pvp_log *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_fashion_info *,obj_fashion_info *>(false,false,std::random_access_iterator_tag);
	void __copy_b<OperatePetInfor *, OperatePetInfor *>(false, false, std::random_access_iterator_tag);
	void copy<obj_friendRoleinfo *,obj_friendRoleinfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<CasinoPet *,CasinoPet *>(false,false,std::random_access_iterator_tag);
	void copy<FashionData const*,FashionData*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_petBattleProp *,obj_petBattleProp *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_realpvp_item *, obj_realpvp_item *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_honorCondInfo *,obj_honorCondInfo *>(false,false,std::random_access_iterator_tag);
	void copy<GuildShopData *,GuildShopData *>(false,false,std::random_access_iterator_tag);
	void copy<monsterWave	const*,	monsterWave*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_pvp_role *, obj_pvp_role *>(false,	false, std::random_access_iterator_tag);
	void copy<PetMonster **, LivingObject	**>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_playerItem	*, obj_playerItem *>(false, false, std::random_access_iterator_tag);
	void copy<chatingContent *,chatingContent *>(false,false,std::random_access_iterator_tag);
	void __copy_b<GashaponMachinesAwardItem *,GashaponMachinesAwardItem *>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_role const*, obj_pvp_role*>(false, false, std::random_access_iterator_tag);
	void copy<TimeLimitKillCopyAward *,TimeLimitKillCopyAward *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_petBattleProp *, obj_petBattleProp	*>(false, false, std::random_access_iterator_tag);
	void copy<MysteriousInfo *,MysteriousInfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_Petpaihangdata *, obj_Petpaihangdata *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_applicant *,	obj_guild_applicant *>(false, false, std::random_access_iterator_tag);
	void __copy_b<notify_role_battle_info	*,notify_role_battle_info *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_mysterious *,obj_mysterious	*>(false,false,std::random_access_iterator_tag);
	void copy<obj_guild_skill const*, obj_guild_skill*>(false, false, std::random_access_iterator_tag);
	void copy<GuildApplyData *, GuildApplyData *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_mysticalmonster *,	obj_mysticalmonster *>(false, false, std::random_access_iterator_tag);
	void copy<TreasureGuildResult	const*,	TreasureGuildResult*>(false, false, std::random_access_iterator_tag);
	void copy<MailData *,MailData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_friendRoleinfo *, obj_friendRoleinfo *>(false, false, std::random_access_iterator_tag);
	void __copy_b<LuckystoneListData *,LuckystoneListData	*>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_role	const*,obj_pvp_role*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_worldnpc_info *, obj_worldnpc_info	*>(false, false, std::random_access_iterator_tag);
	void copy<obj_petBattleProp *,obj_petBattleProp *>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildShopData *,GuildShopData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<ConstellStepDef *, ConstellStepDef *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_updateEquip	*,obj_updateEquip *>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_log const*,obj_pvp_log*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_recharge_info *,obj_recharge_info *>(false,false,std::random_access_iterator_tag);
	void copy<GuildApplyData *,GuildApplyData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildBossLvlDef *, GuildBossLvlDef *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_applicant *,obj_guild_applicant *>(false,false,std::random_access_iterator_tag);
	void copy<TlkMonsterCfgDef const*,TlkMonsterCfgDef*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_totem_info	*, obj_totem_info *>(false, false, std::random_access_iterator_tag);
	void copy<MatchResult *,MatchResult *>(false,false,std::random_access_iterator_tag);
	void __copy_b<PetChooseData *, PetChooseData	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<DiceGrid *,DiceGrid *>(false,false,std::random_access_iterator_tag);
	void copy<TreasureFightRoomInfo *, TreasureFightRoomInfo *>(false, false, std::random_access_iterator_tag);
	void __copy_b<GuildSkillProperty *, GuildSkillProperty *>(false, false, std::random_access_iterator_tag);
	void copy<TreasureGuildResult const*,TreasureGuildResult*>(false,false,std::random_access_iterator_tag);
	void __copy_b<_tagLevelRange *,_tagLevelRange	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_actstat *,obj_actstat *>(false,false,std::random_access_iterator_tag);
	void __copy_b<FashionData *,FashionData *>(false,false,std::random_access_iterator_tag);
	void copy<monsterWave	*, monsterWave *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_worldrole_info *,obj_worldrole_info	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_worldpet_info *,obj_worldpet_info *>(false,false,std::random_access_iterator_tag);
	void copy<obj_copy_resettimes const*,obj_copy_resettimes*>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_log *,obj_pvp_log *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_guild_skill	*,obj_guild_skill *>(false,false,std::random_access_iterator_tag);
	void copy<obj_tlk_monster *, obj_tlk_monster *>(false, false,	std::random_access_iterator_tag);
	void copy<TimeLimitKillCopyAward *, TimeLimitKillCopyAward *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_copyaward *, obj_copyaward	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_guild_log_info *, obj_guild_log_info *>(false, false, std::random_access_iterator_tag);
	void copy<obj_honorInfo const*,obj_honorInfo*>(false,false,std::random_access_iterator_tag);
	void __copy_b<PetStageQua *,PetStageQua *>(false,false,std::random_access_iterator_tag);
	void copy<obj_tlk_monster const*, obj_tlk_monster*>(false, false, std::random_access_iterator_tag);
	void copy<obj_skill_effect_info *,obj_skill_effect_info *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_petinfo *,obj_petinfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_guild_member *,obj_guild_member *>(false,false,std::random_access_iterator_tag);
	void __copy_b<addValueDesc *,addValueDesc *>(false,false,std::random_access_iterator_tag);
	void copy<obj_copy_resettimes	const*,	obj_copy_resettimes*>(false, false, std::random_access_iterator_tag);
	void copy<obj_mysticalmonster *,obj_mysticalmonster *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_worldpet_info *, obj_worldpet_info	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<GuildApplyData	*, GuildApplyData *>(false, false, std::random_access_iterator_tag);
	void __copy_b<Dialog *,Dialog	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<TreasureFightRoomInfo *, TreasureFightRoomInfo	*>(false, false, std::random_access_iterator_tag);
	void copy<obj_honorInfo *, obj_honorInfo *>(false, false, std::random_access_iterator_tag);
	void __copy_b<StarCfgDef *, StarCfgDef *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_petinfo *,	obj_petinfo *>(false, false, std::random_access_iterator_tag);
	void copy<obj_mysticalmonster	const*,	obj_mysticalmonster*>(false, false, std::random_access_iterator_tag);
	void copy<Server const*,Server*>(false,false,std::random_access_iterator_tag);
	void copy<TlkMonsterCfgDef *,TlkMonsterCfgDef *>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildMemberData *, GuildMemberData *>(false, false, std::random_access_iterator_tag);
	void copy<obj_honorInfo *,obj_honorInfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_worldfly_info *, obj_worldfly_info	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<OperatePetInfor	*,OperatePetInfor *>(false,false,std::random_access_iterator_tag);
	void __copy_b<notify_role_battle_info *, notify_role_battle_info *>(false, false, std::random_access_iterator_tag);
	void __copy_b<monsterWave *,	monsterWave *>(false, false, std::random_access_iterator_tag);
	void copy<obj_petBattleProp *, obj_petBattleProp *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_attackedTarget *, obj_attackedTarget *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_fashion_info *, obj_fashion_info *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_fames_info *,obj_fames_info	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<RankData *,RankData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_lotteryhistory *, obj_lotteryhistory *>(false, false, std::random_access_iterator_tag);
	void __copy_b<UpdatePackageDef *,UpdatePackageDef *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_honorInfo *,obj_honorInfo *>(false,false,std::random_access_iterator_tag);
	void copy<TreasureFightRoomInfo *,TreasureFightRoomInfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_getscore *, obj_treasurecopy_getscore	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<PetStageQua *,	PetStageQua *>(false, false, std::random_access_iterator_tag);
	void __copy_b<IllustrationsState *, IllustrationsState *>(false, false, std::random_access_iterator_tag);
	void copy<obj_lotteryhistory *, obj_lotteryhistory *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_lotteryhistory *,obj_lotteryhistory	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<ItemGroup *, ItemGroup	*>(false, false, std::random_access_iterator_tag);
	void copy<TimeLimitKillCopyAward const*,TimeLimitKillCopyAward*>(false,false,std::random_access_iterator_tag);
	void copy<PetList *,PetList *>(false,false,std::random_access_iterator_tag);
	void __copy_b<void (false,false,std::random_access_iterator_tag);
	void __copy_b<teamInfor *,teamInfor *>(false,false,std::random_access_iterator_tag);
	void __copy_b<SysTotemGroupTotem *, SysTotemGroupTotem *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_bagItem *,	obj_bagItem *>(false, false, std::random_access_iterator_tag);
	void copy<IllustrationsState const*, IllustrationsState*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_illustrationsInfo *, obj_illustrationsInfo	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<Constellation *, Constellation	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_treasure_scene *, obj_treasure_scene *>(false, false, std::random_access_iterator_tag);
	void copy<QueenBlessing *,QueenBlessing *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_guildresult *,obj_treasurecopy_guildresult *>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildListData *,GuildListData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_addordelItem *, obj_addordelItem *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<TreasureFightRoomInfo *,TreasureFightRoomInfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<Constellation *,Constellation *>(false,false,std::random_access_iterator_tag);
	void copy<RoleEquipSkill *,RoleEquipSkill *>(false,false,std::random_access_iterator_tag);
	void __copy_b<StarCfgDef *,StarCfgDef	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<MysteriousInfo *,MysteriousInfo	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_rankdata *,obj_treasurecopy_rankdata *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_friendDunge_record *,obj_friendDunge_record	*>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_log	const*,	obj_pvp_log*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_skill_effect_info *, obj_skill_effect_info	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_item *,obj_item *>(false,false,std::random_access_iterator_tag);
	void copy<obj_pvp_role	*,obj_pvp_role *>(false,false,std::random_access_iterator_tag);
	void copy<obj_guild_skill *,obj_guild_skill *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_manor	*, obj_treasurecopy_manor *>(false, false, std::random_access_iterator_tag);
	void __copy_b<SkillHurt *,SkillHurt *>(false,false,std::random_access_iterator_tag);
	void __copy_b<MailData *,MailData *>(false,false,std::random_access_iterator_tag);
	void copy<chatingContent *, chatingContent *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_monster_average_hurt *,obj_monster_average_hurt *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_dungeawawrd	*,obj_dungeawawrd *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_manor *,obj_treasurecopy_manor	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_casino_pet *,obj_casino_pet	*>(false,false,std::random_access_iterator_tag);
	void copy<addValueDesc	*,addValueDesc *>(false,false,std::random_access_iterator_tag);
	void copy<Server *, Server *>(false, false, std::random_access_iterator_tag);
	void copy<GuildMemberData *, GuildMemberData *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<TlkMonsterCfgDef *,TlkMonsterCfgDef *>(false,false,std::random_access_iterator_tag);
	void __copy_b<_SynArenaShopData *, _SynArenaShopData	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_capsuletoy_info *,	obj_capsuletoy_info *>(false, false, std::random_access_iterator_tag);
	void copy<ItemGroup *,ItemGroup *>(false,false,std::random_access_iterator_tag);
	void __copy_b<ConstellStepDef	*,ConstellStepDef *>(false,false,std::random_access_iterator_tag);
	void __copy_b<RoleEquipSkill *,RoleEquipSkill	*>(false,false,std::random_access_iterator_tag);
	void copy<TreasureGuildResult	*, TreasureGuildResult *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<QueenBlessing *,QueenBlessing *>(false,false,std::random_access_iterator_tag);
	void copy<FashionData	*, FashionData *>(false, false,	std::random_access_iterator_tag);
	void copy<monsterWave const*,monsterWave*>(false,false,std::random_access_iterator_tag);
	void copy<obj_petBattleProp const*,obj_petBattleProp*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_realpvp_item *,obj_realpvp_item *>(false,false,std::random_access_iterator_tag);
	void copy<MailData *,	MailData *>(false, false, std::random_access_iterator_tag);
	void copy<obj_roleinfo	*,obj_roleinfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_equiped_skill *, obj_equiped_skill	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<_tagLevelRange	*, _tagLevelRange *>(false, false, std::random_access_iterator_tag);
	void copy<addValueDesc	const*,addValueDesc*>(false,false,std::random_access_iterator_tag);
	void copy<obj_friendRoleinfo *, obj_friendRoleinfo *>(false, false, std::random_access_iterator_tag);
	void __copy_b<_SynArenaShopData *,_SynArenaShopData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_casino_pet	*, obj_casino_pet *>(false, false, std::random_access_iterator_tag);
	void copy<MatchResult	*, MatchResult *>(false, false,	std::random_access_iterator_tag);
	void copy<PetList *, PetList *>(false, false,	std::random_access_iterator_tag);
	void __copy_b<obj_posiinfo *,obj_posiinfo *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_mysteriousInfo *, obj_mysteriousInfo *>(false, false, std::random_access_iterator_tag);
	void __copy_b<MatElement *, MatElement *>(false, false, std::random_access_iterator_tag);
	void copy<addValueDesc *, addValueDesc *>(false, false, std::random_access_iterator_tag);
	void copy<ItemGroup *, ItemGroup *>(false, false, std::random_access_iterator_tag);
	void __copy_b<IllustraData *,IllustraData *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_mysterious	*, obj_mysterious *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_fames_info	*, obj_fames_info *>(false, false, std::random_access_iterator_tag);
	void __copy_b<GuildNewsData *,GuildNewsData *>(false,false,std::random_access_iterator_tag);
	void copy<QueenBlessing *, QueenBlessing *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_posiinfo *, obj_posiinfo *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_hurts *,obj_hurts *>(false,false,std::random_access_iterator_tag);
	void copy<obj_guild_skill const*,obj_guild_skill*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_paihangdata	*,obj_paihangdata *>(false,false,std::random_access_iterator_tag);
	void __copy_b<PetList *, PetList *>(false, false, std::random_access_iterator_tag);
	void __copy_b<TreasureScoreData *, TreasureScoreData	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_bagItem *,obj_bagItem *>(false,false,std::random_access_iterator_tag);
	void __copy_b<DiceGrid *, DiceGrid *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_playerItem *,obj_playerItem	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_guildresult *, obj_treasurecopy_guildresult *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_actstat *,	obj_actstat *>(false, false, std::random_access_iterator_tag);
	void __copy_b<obj_friendRoleinfo *,obj_friendRoleinfo	*>(false,false,std::random_access_iterator_tag);
	void __copy_b<GuildListData *, GuildListData	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<GashaponMachinesAwardItem *, GashaponMachinesAwardItem	*>(false, false, std::random_access_iterator_tag);
	void __copy_b<PetEliteInfor *,PetEliteInfor *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_mysticalcopy *, obj_mysticalcopy *>(false,	false, std::random_access_iterator_tag);
	void __copy_b<obj_equiped_skill *,obj_equiped_skill *>(false,false,std::random_access_iterator_tag);
	void __copy_b<obj_treasurecopy_getscore *,obj_treasurecopy_getscore *>(false,false,std::random_access_iterator_tag);
	void copy<TlkMonsterCfgDef const*, TlkMonsterCfgDef*>(false, false, std::random_access_iterator_tag);
}
#endif