#ifndef MOF_UIMGR_H
#define MOF_UIMGR_H

class UIMgr{
public:
	void removeAllLayer(void);
	void showFail(std::string,int);
	void showPetMatchUI(void);
	void getSystemMonTime(long);
	void showGuildApply(void);
	void showFamousTips(bool, std::string);
	void CreateCCLabelTTF(char const*,char const*,cocos2d::CCPoint,cocos2d::CCPoint,cocos2d::CCNode *);
	void showFamousTips(bool,int,int);
	void LoadCharactersFile(char const*);
	void showPetArenaUI(void);
	void showPetMonsterUI(bool,	int);
	void battleMode(void);
	void showOneBtnCommonDialog(cocos2d::CCObject	*),std::string);
	void showActivity(std::vector<int, std::allocator<int>>, long);
	void getSystemYearTime(long);
	void showDeleteRleDailog(cocos2d::CCObject *), std::string, std::string);
	void showFail(std::string, int);
	void showTeamWithFriendsUI(eSceneType);
	void removeLayer(cocos2d::CCLayer *);
	void showTreasureFightDeadDetailUI(std::string);
	void showNewguidanceByStep(int);
	void showTakeOnEquipByStep(int,int);
	void getSystemWeek(long);
	void createCEditBox(char const*,cocos2d::extension::CCEditBoxDelegate *,int,int,int,int);
	void showTreasureFightUI(void);
	void CreateCCLabelTTFs(char	const*,char const*,cocos2d::CCPoint,cocos2d::CCPoint,cocos2d::CCNode *);
	void LoadExpressionFile(char const*);
	void clearAllData(void);
	void showGuildBossTips(bool,int,int);
	void showNewConfirmDialog(std::string, int,	std::string, std::string);
	void showGuildSkill(void);
	void showBattleDialog(int,int,DialogState);
	void createSomeColorLabel(std::string, float *);
	void showDungeonsUI(eSceneType);
	void CreateCCSprite(int, int, float, float);
	void showSynPvpArenaTipUI(bool,int,int);
	void CreateCCLabelTTF(char const*, char const*, cocos2d::CCPoint, cocos2d::CCPoint,	cocos2d::CCNode	*);
	void getSystemTime(long);
	void hideLayer(cocos2d::CCLayer *);
	void showPetCollectUI(int,IllustrationsQuality);
	void showArenaTipUI(bool,int,int);
	void showSynPvpResult(bool);
	void showVipUI(void);
	void showBulkExchangeDialog(cocos2d::CCObject *),int,cocos2d::CCSprite	*,int);
	void showNewSystemPromptUI(int);
	void showBulkExchangeDialog(cocos2d::CCObject *), int, cocos2d::CCSprite *, int);
	void getstringFromImageresourcesini(char const*,char const*);
	void showArenaUI(void);
	void showCommonDialog(cocos2d::CCObject *),std::string,std::string);
	void showStarUI(void);
	void CreateCCSprite(int, float,	float);
	void createSomeColorWrapLabel(std::string,float,float,float	*);
	void showDeleteRleDailog(cocos2d::CCObject *),std::string,std::string);
	void showLoginAwardUI(int, bool, bool, awardTap);
	void createSomeColorWrapLabel(std::string, float, float, float *);
	void showGuildShop(void);
	void showDiceGameUI(void);
	void showPromptTips(std::vector<std::string,std::allocator<std::string>>,float,cocos2d::CCPoint);
	void showDefendStatue(bool,int,int);
	void CreateCCScale9Sprite(int, int, float, float);
	void showPromptTips(std::string,bool,cocos2d::CCPoint,bool);
	void getstringFromCharactersini(char const*,char const*);
	void showCapsuleToyUI(void);
	void showCommonDialogForSynPvp(cocos2d::CCObject *), std::string,	std::string);
	void ~UIMgr();
	void showSynPvpArenaTipUI(bool, int, int);
	void showChartingDialog(void);
	void showSynPvpStoreExchangeDialog(cocos2d::CCObject	*), int, cocos2d::CCSprite *);
	void showPetCollectUI(int, IllustrationsQuality);
	void showDailyTask(void);
	void loadUIini(void);
	void showHelperUI(void);
	void showCheckPlayerUI(bool);
	void showAutoTestUI(void);
	void showGuildBossTips(bool, int, int);
	void showGuildList(bool);
	void showKillMonsterNum(int, int);
	void showEquipmentUI(void);
	void showShoppingCommonDialog(cocos2d::CCObject *), std::string, cocos2d::CCSprite *);
	void showFamousTips(bool, int, int);
	void showLayer(cocos2d::CCLayer *);
	void showChannelSelect(void);
	void showBulkPurchaseDialog(cocos2d::CCObject *),std::string,cocos2d::CCSprite	*);
	void showNewbie(bool);
	void showGuildNews(void);
	void showQueenBlessingUI(void);
	void createCEditBox(char const*, cocos2d::extension::CCEditBoxDelegate *, int, int,	int, int);
	void SystemAnnouncementCallback(void);
	void LoadImageresourcesFile(char const*);
	void showGuildBossUI(void);
	void showPetArenaTipUI(bool,int,int);
	void getstringFromCharactersini(char const*, char const*);
	void showMysticalCopyUI(void);
	void getPureString(std::string);
	void showFirstChargeUI(void);
	void showOneBtnCommonDialog(cocos2d::CCObject *), std::string);
	void showRankUI(void);
	void isShowingAnyGuildUI(void);
	void showShareUI(void);
	void showPromptTips(std::vector<std::string, std::allocator<std::string>>, float, cocos2d::CCPoint);
	void showSystemAnnouncement(std::string);
	void getPetMonsterDegreeStr(int);
	void showArrowsPromptUI(int);
	void showMailUI(void);
	void openPetEggByNewguidance(int);
	void showPromptTips(std::string, bool, cocos2d::CCPoint, bool);
	void createCProgressTimer(char const*, cocos2d::CCPoint, cocos2d::CCNode *,	cocos2d::CCPoint);
	void showTreasureScoreUI(void);
	void showCityAwardUI(bool);
	void setShowNum(int);
	void showGoGo(void);
	void dropEquipTips(int);
	void showSynPvpStoreExchangeDialog(cocos2d::CCObject *),int,cocos2d::CCSprite *);
	void CreateCCLabelTTFs(char	const*,	char const*, cocos2d::CCPoint, cocos2d::CCPoint, cocos2d::CCNode *);
	void showActivity(std::vector<int,std::allocator<int>>,long);
	void getColorfromInI(QualityColor);
	void getstringFromImageresourcesini(char const*, char const*);
	void showAccumulateAwardUI(void);
	void showPetTotemUI(void);
	void showOneBtnCommonDialogForSynPvp(cocos2d::CCObject *),std::string);
	void showBagUI(void);
	void showAdventureAwardUI(int);
	void showArenaTipUI(bool, int, int);
	void getstringFromExpressionini(char const*,char const*);
	void showoperateUI(void);
	void showNewguidanceOpen(int);
	void showGuildCreate(void);
	void showSynArenaUI(void);
	void showGuildUI(void);
	void showMysticalCopyTimer(int);
	void showDailyAnswerUI(void);
	void showDefendStatue(bool,	int, int);
	void showWritingNetWorkDialog(void);
	void showFamousHallUI(int);
	void CreateCCSprite(char const*,char const*,cocos2d::CCPoint,cocos2d::CCNode *,cocos2d::CCPoint,float,float);
	void showCommonDialogForSynPvp(cocos2d::CCObject *),std::string,std::string);
	void showSystemSettingUI(void);
	void createCProgressTimer(char const*,cocos2d::CCPoint,cocos2d::CCNode *,cocos2d::CCPoint);
	void CreateCCSprite(char const*,cocos2d::CCPoint,cocos2d::CCNode *,cocos2d::CCPoint,float,float);
	void showPetMonsterUI(bool,int);
	void showFunnyActUI(void);
	void showGuildMember(void);
	void showChallenge(bool,int,int,int,bool);
	void addLayer(cocos2d::CCLayer *);
	void showTicketsAcounts(void);
	void showSkillLearningUI(void);
	void LoadCreateUIFile(char const*);
	void showMySticMerchantUI(void);
	void isShowingInnerGuildUI(void);
	void showChargeActivity(void);
	void resetArrowsPromptUI(void);
	void showWorldBossTips(bool,std::string);
	void showTicketActivityUI(int);
	void getstringFromExpressionini(char const*, char const*);
	void showTakeOnEquipByStep(int, int);
	void showWorldBossRestore(int,int);
	void showKillMonsterNum(int,int);
	void hideAllLayer(void);
	void showGuildApplyInMainUI(void);
	void createSomeColorLabel(std::string,float	*);
	void getCharacterTypes(int);
	void showPass(int, int, int, int, bool);
	void showReady(int);
	void deleteWritingNetWorkDialog(void);
	void showAddEnergyDialog(void);
	void stopGoGo(void);
	void showFightState(bool);
	void townMode(void);
	void showPresentByStata(presentStata);
	void showNewConfirmDialog(std::string,int,std::string,std::string);
	void showWorldBossRestore(int, int);
	void showLoginAwardUI(int,bool,bool,awardTap);
	void showBattleDialog(int, int, DialogState);
	void showLevelChooseDialog(int);
	void showTreasureManorsUI(void);
	void showChallenge(bool, int, int, int, bool);
	void showArenaActivityUI(void);
	void deleteNewguidanceArrow(std::string);
	void showPass(int,int,int,int,bool);
	void showPetArenaTipUI(bool, int, int);
	void showOneBtnCommonDialogForSynPvp(cocos2d::CCObject *), std::string);
	void showShoppingCommonDialog(cocos2d::CCObject *),std::string,cocos2d::CCSprite *);
	void showBulkPurchaseDialog(cocos2d::CCObject *), std::string, cocos2d::CCSprite *);
	void showWorldBossTips(bool, std::string);
	void CreateCCScale9Sprite(char const*,char const*,cocos2d::CCPoint,cocos2d::CCNode *,cocos2d::CCPoint,float,float);
	void showCommonDialog(cocos2d::CCObject *), std::string, std::string);
	void getColorString(QualityColor);
	void showMonthCardUI(int);
	void showTitleTip(void);
	void showFamousTips(bool,std::string);
	void showFailAward(void);
	void isShowingOuterGuildUI(void);
	void showOrdinaryActivityUI(void);
	void showSweepUI(int);
}
#endif