
 module("NotificationNames", package.seeall)

 EVT_BACKGROUND_INI                      = "EVT_BACKGROUND_INI" 			-- 初始化背景
 EVT_BACKGROUND_SCROLL_START             = "EVT_BACKGROUND_SCROLL" 			-- 开始滚动  
 EVT_BACKGROUND_SET_POSTION              = "EVT_BACKGROUND_SET_POSTION" 	-- 设置滚动位置
 EVT_BACKGROUND_SCROLL_COMPLETE          = "EVT_BACKGROUND_SCROLL_COMPLETE" -- 滚动动画结束
 EVT_BACKGROUND_SET_CONTAINER			 = "EVT_BACKGROUND_SET_CONTAINER" 	-- 设置背景容器

 EVT_STRONGHOLD_INI 					 = "EVT_STRONGHOLD_INI"				-- 初始化 strongHold
 EVT_STRONGHOLD_START_INI				 = "EVT_STRONGHOLD_START_INI"		-- 战斗初始化控制器初始化
 EVT_STRONGHOLD_START_INI_COMPLETE		 = "EVT_STRONGHOLD_START_INI_COMPLETE"		-- 战斗初始化控制器初始化

 EVT_SINGLE_BATTLE_INI					 = "EVT_SINGLE_BATTLE_INI"			-- 初始化单场战斗

 EVT_FORMATION_INI 						 = "EVT_FORMATION_INI"				-- 初始化 阵型数据
 EVT_FORMATION_GET 			 			 = "EVT_FORMATION_GET"				-- 初始化 获取当前阵型数据
 EVT_FORMATION_GET_SUCESS 				 = "EVT_FORMATION_GET_SUCESS"		-- 阵型获取成功
 EVT_FORMATION_START_CONFIG 			 = "EVT_FORMATION_START_CONFIG"		-- 开始配置阵型
 EVT_FORMATION_COMPLETE_CONFIG			 = "EVT_FORMATION_COMPLETE_CONFIG"	-- 配置阵型结束

 EVT_SC_FORMATION_DATA_COMPLETE			 = "EVT_SC_FORMATION_DATA_COMPLETE"	-- 阵型数据完成

 EVT_BATTLE_REQUEST				 	 	 = "EVT_REQUEST_BATTLE"				-- 请求战斗
 EVT_BATTLE_REQUEST_COMPLETE			 = "EVT_BATTLE_REQUEST_COMPLETE"	-- 战斗数据完成

 EVT_BATTLE_RECORD_PLAY_START			 = "EVT_BATTLE_RECORD_START_PLAY" 	-- 开始播放战斗录像
 EVT_BATTLE_RECORD_PLAY_COMPLETE	 	 = "EVT_BATTLE_RECORD_START_PLAY" 	-- 战斗录像播放完毕

 EVT_EXCUTE_SKILL						 = "EVT_EXCUTE_SKILL"				-- 激活技能


 EVT_RESULT_WIN_SHOW 					 = "EVT_RESULT_WIN_SHOW"			-- 显示结束面板
 EVT_RESULT_WIN_CLOSE					 = "EVT_RESULT_WIN_CLOSE"			-- 关闭结束面板


 EVT_ENTER_LEVEL_START					 = "EVT_ENTER_LEVEL_START"
 EVT_ENTER_LEVEL_SUCCESS				 = "EVT_ENTER_LEVEL_SUCCESS"
 EVT_ENTER_LEVEL_FAILED				 	 = "EVT_ENTER_LEVEL_FAILED"


 EVT_DO_BATTLE_SUCCESS 					 = "EVT_DO_BATTLE_SUCCESS"
 EVT_DO_BATTLE_FAILED 					 = "EVT_DO_BATTLE_FAILED"


 EVT_SKILL_DAMAGE 						 = "EVT_SKILL_DAMAGE"


 EVT_SKILL_NODE_ACTIVE					 = "EVT_SKILL_NODE_ACTIVE"

 EVT_BATTLE_SKIP_RECORD 				 = "EVT_BATTLE_SKIP_RECORD"

 EVT_BATTLE_AUTO_FIGHT					 = "EVT_BATTLE_AUTO_FIGHT"

 EVT_BATTLE_SHOW_BG_EFFECT 				 = "EVT_BATTLE_SHOW_BG_EFFECT"

 EVT_QUIT_BATTLE 						 = "EVT_BATTLE_QUIT"



 EVT_RECORD_PLAY_NEXT_PLAYER_ROUND 		 = "EVT_RECORD_PLAY_NEXT_PLAYER_ROUND"


--------------------------  data 
 -- 请求战斗数据完成(副本用)
 EVT_BATTLE_REQUEST_DATA_SUCCESS		 = "EVT_BATTLE_REQUEST_DATA_SUCCESS"


-------------------------- revived

EVT_REVIVED_SUCCESS						 = "EVT_REVIVED_SUCCESS" --复活英雄成功
EVT_REVIVED_FAILED						 = "EVT_REVIVED_FAILED"  --复活英雄失败

-------------------------- record 

 EVT_PLAY_RECORD_START 					 = "EVT_PLAY_RECORD_START" 
 EVT_PLAY_RECORD_COMPLETE 				 = "EVT_PLAY_RECORD_COMPLETE"

 EVT_RECORD_PAUSED 						 = "EVT_RECORD_PAUSED" -- 战斗暂停
 EVT_RECORD_CONTINUE_PLAY				 = "EVT_RECORD_CONTINUE_PLAY" -- 继续播放战斗
 -- EVT_DISPOSE 							 = "EVT_DISPOSE"
 ------------------------- team show

 EVT_TEAM_SHOW_START					 = "EVT_TEAM_SHOW_START"
 EVT_TEAM_SHOW_COMPLETE					 = "EVT_TEAM_SHOW_COMPLETE"


 EVT_TEAM_ENDSHOW_START					 = "EVT_TEAM_ENDSHOW_START"
 EVT_TEAM_ENDSHOW_COMPLETE				 = "EVT_TEAM_ENDSHOW_COMPLETE"

 -------------------------- result window

 EVT_SHOW_RESULT_WINDOW					 = "EVT_SHOW_RESULT_WINDOW"
 EVT_CLOSE_RESULT_WINDOW				 = "EVT_CLOSE_RESULT_WINDOW"
 EVT_REPLAY_RECORD						 = "EVT_REPLAY_RECORD" 	-- 重播

 EVT_REQUEST_QUIT_BATTLE 				= "EVT_REQUEST_QUIT_BATTLE"

 EVT_SHOW_STRENGTHEN_EQUIP 				= "EVT_SHOW_STRENGTHEN_EQUIP" -- 战斗失败 显示 强化装备面板
 EVT_SHOW_STRENGTHEN_HERO 				= "EVT_SHOW_STRENGTHEN_HERO" -- 战斗失败 显示 强化英雄面板
 EVT_SHOW_TRAIN_STAR 					= "EVT_SHOW_TRAIN_STAR" -- 战斗失败 显示 培养名 将面板
 EVT_SHOW_FEED_PET 						= "EVT_SHOW_FEED_PET" -- 战斗失败 显示 喂养宠物 面板
 -------------------------- talk
 EVT_TALK_PLAY_TALK						= "EVT_TALK_PLAY_TALK"			-- 开始播放对话
 EVT_TALK_PLAY_TALK_COMPLETE 			= "EVT_TALK_PLAY_TALK_COMPLETE" -- 对话播放完毕
 EVT_TALK_SET_TALK_BG					= "EVT_TALK_SET_TALK_BG" 	-- 设置对话触发背景替换表
 EVT_TALK_SET_TALK_MUSIC				= "EVT_TALK_SET_TALK_MUSIC" -- 设置对话触发音乐替换表
 

 EVT_TALK_REQUEST_CHANGE_BG		= "EVT_TALK_REQUEST_CHANGE_TALK_BG"
 EVT_TALK_REQUEST_CHANGE_BG_END	= "EVT_TALK_REQUEST_CHANGE_TALK_BG_END"
 
 EVT_TALK_REQUEST_CHANGE_MUSIC			= "EVT_TALK_REQUEST_CHANGE_MUSIC"
 EVT_TALK_REQUEST_CHANGE_MUSIC_END		= "EVT_TALK_REQUEST_CHANGE_MUSIC_END"
 --------------------------  info ui


 EVT_REFRESH_SH_RESULT 					= "EVT_REFRESH_SH_RESULT" -- 刷新sh(据点)结束数据

 


 -- EVT_REVIVE_HERO_COMPLETE 				= "EVT_REVIVE_HERO_COMPLETE" --复活英雄成功
 -- EVT_REVIVE_HERO_ERROR 					= "EVT_REVIVE_HERO_ERROR" 	--复活英雄失败
 EVT_UI_INI 							= "EVT_UI_INI"
 EVT_UI_SHOW_SPEED_BT					= "EVT_UI_SHOW_SPEED_BT"	-- 显示加速按钮
 EVT_UI_SHOW_SKIP_BT					= "EVT_UI_SHOW_SKIP_BT" 	-- 显示调过战斗按钮
 EVT_UI_REMOVE_SKIP_BT					= "EVT_UI_REMOVE_SKIP_BT"	-- 删除调过战斗按钮
 EVT_UI_SHOW_AUTO_FIGHT					= "EVT_UI_SHOW_AUTO_FIGHT"  -- 自动战斗
 EVT_UI_REMOVE_SPEED_BT 				= "EVT_UI_REMOVE_SPEED_BT"	-- 删除加速按钮

 -- EVT_UI_REFRESH_RESOURCE				= "EVT_UI_REFRESH_RESOURCE" -- 累加 掉落英雄(碎片)
 -- EVT_UI_REFRESH_SOUL					= "EVT_UI_REFRESH_SOUL"		-- 累加 魂玉
 -- EVT_UI_REFRESH_MONEY					= "EVT_UI_REFRESH_MONEY"    -- 累加 钱
 EVT_UI_REFRESH_ROUND					= "EVT_UI_REFRESH_ROUND"    -- 设置 回合
 EVT_UI_REFRESH_ITEM 					= "EVT_UI_REFRESH_ITEM"		-- 累加 物品
 
 EVT_UI_SET_HERO_PART_TO				= "EVT_UI_SET_HERO_PART_TO" -- 设置 掉落英雄(碎片)
 EVT_UI_SET_ITEM_TO						= "EVT_UI_SET_ITEM_TO" 		-- 设置 掉落物品
 
 EVT_UI_REFRESH_CHEST_DATA 				= "EVT_UI_REFRESH_CHEST_DATA" -- 刷新箱子掉落数据(英雄碎片,物品)

  -------------------------- load

 EVT_LOAD_START_PRELOAD_START 			= "EVT_LOAD_START_PRELOAD_START"
 EVT_LOAD_START_PRELOAD_COMPLETE		= "EVT_LOAD_START_PRELOAD_COMPLETE"
 EVT_LOAD_START_ROUND 					= "EVT_LOAD_START_ROUND"
 EVT_LOAD_START_ROUND_COMPLETE 			= "EVT_LOAD_START_ROUND_COMPLETE"



 -------------------------- change scene

 EVT_CHANGE_SCENE_START 					= "EVT_10001"
 EVT_CHANGE_SCENE_READY 					= "EVT_10002"
 EVT_CHANGE_SCENE_COMPLETE 					= "EVT_10003"
 EVT_SINGLE_BATTLE_CHANGE_SCENE_START 		= "EVT_10004"
 EVT_SINGLE_BATTLE_CHANGE_SCENE_COMPLETE 	= "EVT_10005"
 EVT_SINGLE_BATTLE_TOPSHOW_CHANGE_SCENE_START  = "EVT_10006"

 EVT_CHANGE_SCENE_PAUSE 					= "EVT_10007" -- 切换场景暂停
 EVT_CHANGE_SCENE_RESUME 					= "EVT_10008" -- 切换场景继续
 EVT_SINGLE_CHANGE_SCENE_RESUME 			= "EVT_SINGLE_CHANGE_SCENE_RESUME" -- 单场切换场景继续

--------------------------- battle show
 EVT_REQUEST_CHANGE_BG_DIRECT 			= "EVT_REQUEST_CHANGE_BG_DIRECT" 	-- 直接切换背景
 EVT_REQUEST_CHANGE_MUSIC_DIRECT 		= "EVT_REQUEST_CHANGE_MUSIC_DIRECT" -- 直接切换音乐

 ------------------------- 鼠标显示名字

 EVT_ENABLE_TOUCH_SHOW_NAME				= "EVT_ENABLE_TOUCH_SHOW_NAME"
 EVT_DISABLE_TOUCH_SHOW_NAME			= "EVT_DISABLE_TOUCH_SHOW_NAME"


 ------------------------- 箱子飞

 EVT_CHEST_ADD 							= "EVT_CHEST_ADD"

 EVT_CHEST_DISPOSE						= "EVT_CHEST_DISPOSE" 	-- 销毁所有

 EVT_CHEST_UNUSE_ALL					= "EVT_CHEST_UNUSE_ALL" 		-- 废弃所有正在执行的数据(结束面板出现时,动画显示一样飞,但是数据失效)

 -- EVT_UI_
 -------------------------  替补
 EVT_UI_BENCH_ADD						= "EVT_UI_BENCH_INI"
 EVT_UI_BENCH_REFRESH_ALIVE_NUM			= "EVT_UI_BENCH_REFRESH_ALIVE_NUM"  -- 刷新存活数量
 EVT_UI_BENCH_HIDE						= "EVT_UI_BENCH_HIDE"
 EVT_UI_BENCH_SHOW						= "EVT_UI_BENCH_SHOW"
 EVT_UI_BENCH_REMOVE					= "EVT_UI_BENCH_REMOVE"
 EVT_UI_BENCH_SHOW_REVIVE				= "EVT_UI_BENCH_SHOW_REVIVE"
 EVT_UI_BENCH_REMOVE_REVIVE				= "EVT_UI_BENCH_REMOVE_REVIVE"
 EVT_UI_BENCH_INI_FROM_BATTLE_STRING	= "EVT_UI_BENCH_INI_FROM_BATTLE_STRING" -- 用战斗串来初始化
 EVT_UI_BENCH_INI_FROM_DATACACHE		= "EVT_UI_BENCH_INI_FROM_DATACACHE" -- 用dataCache来初始化
 EVT_UI_BENCH_ENABLE_REVIVE				= "EVT_UI_BENCH_ENABLE_REVIVE" -- 用dataCache来初始化
 EVT_UI_BENCH_DISABLE_REVIVE			= "EVT_UI_BENCH_DISABLE_REVIVE" -- 用dataCache来初始化
 EVT_UI_BENCH_REVIVE_SUCCESS			= "EVT_UI_BENCH_REVIVE_SUCCESS" -- 复活成功
 EVT_UI_BENCH_REQUEST_REVIVE			= "EVT_UI_BENCH_REQUEST_REVIVE" -- 请求复活替补

--------------------------  活动副本
EVT_BELLY_EVENT_INFO_ADD				= "EVT_BELLY_EVENT_INFO_ADD"
EVT_BELLY_EVENT_INFO_REMOVE				= "EVT_BELLY_EVENT_INFO_REMOVE"
EVT_BELLY_EVENT_INFO_REFRESH_DAMAGE		= "EVT_BELLY_EVENT_INFO_REFRESH_DAMAGE"

