

GameGuideAnims = class()

function GameGuideAnims:handclickAnim(delay, fade)
	delay = delay or 1.8
	fade = fade or 0.1
	local anim = Sprite:createEmpty()
	local hand1 = Sprite:createWithSpriteFrameName("guide_hand_up0000")
	local hand2 = Sprite:createWithSpriteFrameName("guide_hand_down0000")
	local ring = Sprite:createWithSpriteFrameName("guide_hand_ring0000")
	hand1:setAnchorPoint(ccp(1, 0))
	hand2:setAnchorPoint(ccp(1, 0))
	ring:setAnchorPoint(ccp(0.5, 0.5))
	hand1:setPosition(ccp(150, -120))
	hand2:setPosition(ccp(150, -120))
	hand1:runAction(CCMoveBy:create(0, ccp(40, -80)))
	hand1:setOpacity(0)
	hand2:setOpacity(0)
	ring:setOpacity(0)

	local function onDelayOver()
		local actions1 = CCArray:create()
		actions1:addObject(CCFadeIn:create(fade))
		actions1:addObject(CCDelayTime:create(0.2))
		actions1:addObject(CCMoveBy:create(0.2, ccp(-40, 80)))
		actions1:addObject(CCRotateBy:create(0.2, 20))
		actions1:addObject(CCDelayTime:create(0.1))
		actions1:addObject(CCFadeOut:create(0))
		actions1:addObject(CCDelayTime:create(0.2))
		actions1:addObject(CCRotateBy:create(0, -20))
		actions1:addObject(CCDelayTime:create(fade + 2))
		actions1:addObject(CCMoveBy:create(0, ccp(40, -80)))
		hand1:runAction(CCRepeatForever:create(CCSequence:create(actions1)))
		local actions2 = CCArray:create()
		actions2:addObject(CCDelayTime:create(0.7 + fade))
		actions2:addObject(CCFadeIn:create(0))
		actions2:addObject(CCDelayTime:create(0.2))
		actions2:addObject(CCFadeOut:create(fade))
		actions2:addObject(CCDelayTime:create(2))
		hand2:runAction(CCRepeatForever:create(CCSequence:create(actions2)))
		local action3 = CCArray:create()
		action3:addObject(CCDelayTime:create(0.7 + fade))
		action3:addObject(CCScaleTo:create(0, 0.1))
		action3:addObject(CCFadeIn:create(0))
		action3:addObject(CCSpawn:createWithTwoActions(CCScaleTo:create(0.2 + fade, 1.3), CCFadeOut:create(0.2 + fade)))
		action3:addObject(CCDelayTime:create(2))
		ring:runAction(CCRepeatForever:create(CCSequence:create(action3)))
	end

	anim:runAction(CCSequence:createWithTwoActions(CCDelayTime:create(delay), CCCallFunc:create(onDelayOver)))

	anim:addChild(hand1)
	anim:addChild(hand2)
	anim:addChildAt(ring, 0)
	return anim
end

function GameGuideAnims:handslideAnim(from, to, delay, fade)
	delay = delay or 0.9
	fade = fade or 0.1
	local anim = Sprite:createEmpty()
	local hand1 = Sprite:createWithSpriteFrameName("guide_hand_up0000")
	local hand2 = Sprite:createWithSpriteFrameName("guide_hand_down0000")
	local ring = Sprite:createWithSpriteFrameName("guide_hand_ring0000")
	hand1:setAnchorPoint(ccp(1, 0))
	hand2:setAnchorPoint(ccp(1, 0))
	ring:setAnchorPoint(ccp(0.5, 0.5))
	hand1:setPosition(ccp(150, -120))
	hand2:setPosition(ccp(150, -120))
	hand1:setOpacity(0)
	hand2:setOpacity(0)
	ring:setOpacity(0)
	anim:addChild(hand1)
	anim:addChild(hand2)
	anim:addChildAt(ring, 0)
	anim:setPosition(ccp(from.x, from.y))

	local function onDelayOver()
		local actions1 = CCArray:create()
		actions1:addObject(CCFadeIn:create(fade))
		actions1:addObject(CCDelayTime:create(0.2))
		actions1:addObject(CCRotateBy:create(0.1, 20))
		actions1:addObject(CCRotateBy:create(0.1, -20))
		actions1:addObject(CCFadeOut:create(0))
		actions1:addObject(CCDelayTime:create(2.8 + fade))
		hand1:runAction(CCRepeatForever:create(CCSequence:create(actions1)))
		local actions2 = CCArray:create()
		actions2:addObject(CCDelayTime:create(0.4 + fade))
		actions2:addObject(CCFadeIn:create(0))
		actions2:addObject(CCDelayTime:create(0.8))
		actions2:addObject(CCFadeOut:create(fade))
		actions2:addObject(CCDelayTime:create(2))
		hand2:runAction(CCRepeatForever:create(CCSequence:create(actions2)))
		local actions3 = CCArray:create()
		actions3:addObject(CCDelayTime:create(0.4 + fade))
		actions3:addObject(CCScaleTo:create(0, 0.1))
		actions3:addObject(CCFadeIn:create(0))
		actions3:addObject(CCScaleTo:create(0.1, 1.3))
		actions3:addObject(CCScaleTo:create(0.1, 1))
		actions3:addObject(CCDelayTime:create(0.6))
		actions3:addObject(CCSpawn:createWithTwoActions(CCScaleTo:create(fade, 1.3), CCFadeOut:create(fade)))
		actions3:addObject(CCDelayTime:create(2))
		ring:runAction(CCRepeatForever:create(CCSequence:create(actions3)))
		local action = CCArray:create()
		action:addObject(CCMoveTo:create(0, ccp(from.x, from.y)))
		action:addObject(CCDelayTime:create(0.7 + fade))
		action:addObject(CCMoveTo:create(0.5, ccp(to.x, to.y)))
		action:addObject(CCDelayTime:create(fade + 2))
		anim:runAction(CCRepeatForever:create(CCSequence:create(action)))
	end

	anim:runAction(CCSequence:createWithTwoActions(CCDelayTime:create(delay), CCCallFunc:create(onDelayOver)))

	return anim
end

function GameGuideAnims:handcurveSlideAnim(from, to, distance, delay)
	delay = delay or 0.9
	fade = fade or 0.1
	local anim = Sprite:createEmpty()
	local hand1 = Sprite:createWithSpriteFrameName("guide_hand_up0000")
	local hand2 = Sprite:createWithSpriteFrameName("guide_hand_down0000")
	local ring = Sprite:createWithSpriteFrameName("guide_hand_ring0000")
	hand1:setAnchorPoint(ccp(1, 0))
	hand2:setAnchorPoint(ccp(1, 0))
	ring:setAnchorPoint(ccp(0.5, 0.5))
	hand1:setPosition(ccp(150, -120))
	hand2:setPosition(ccp(150, -120))
	hand1:setOpacity(0)
	hand2:setOpacity(0)
	ring:setOpacity(0)
	anim:addChild(hand1)
	anim:addChild(hand2)
	anim:addChildAt(ring, 0)
	anim:setPosition(ccp(from.x, from.y))

	local function onDelayOver()
		local actions1 = CCArray:create()
		actions1:addObject(CCFadeIn:create(fade))
		actions1:addObject(CCDelayTime:create(0.2))
		actions1:addObject(CCRotateBy:create(0.1, 20))
		actions1:addObject(CCRotateBy:create(0.1, -20))
		actions1:addObject(CCFadeOut:create(0))
		actions1:addObject(CCDelayTime:create(3.3 + fade))
		hand1:runAction(CCRepeatForever:create(CCSequence:create(actions1)))
		local actions2 = CCArray:create()
		actions2:addObject(CCDelayTime:create(0.4 + fade))
		actions2:addObject(CCFadeIn:create(0))
		actions2:addObject(CCDelayTime:create(1.3))
		actions2:addObject(CCFadeOut:create(fade))
		actions2:addObject(CCDelayTime:create(2))
		hand2:runAction(CCRepeatForever:create(CCSequence:create(actions2)))
		local actions3 = CCArray:create()
		actions3:addObject(CCDelayTime:create(0.4 + fade))
		actions3:addObject(CCScaleTo:create(0, 0.1))
		actions3:addObject(CCFadeIn:create(0))
		actions3:addObject(CCScaleTo:create(0.1, 1.3))
		actions3:addObject(CCScaleTo:create(0.1, 1))
		actions3:addObject(CCDelayTime:create(1.1))
		actions3:addObject(CCSpawn:createWithTwoActions(CCScaleTo:create(fade, 1.3), CCFadeOut:create(fade)))
		actions3:addObject(CCDelayTime:create(2))
		ring:runAction(CCRepeatForever:create(CCSequence:create(actions3)))
		local action = CCArray:create()
		action:addObject(CCMoveTo:create(0, ccp(from.x, from.y)))
		action:addObject(CCDelayTime:create(0.7 + fade))
		local function bezier()
			anim:runAction(HeBezierTo:create(1, ccp(to.x, to.y), distance > 0, math.abs(distance)))
		end
		action:addObject(CCCallFunc:create(bezier))
		action:addObject(CCDelayTime:create(1))
		action:addObject(CCDelayTime:create(fade + 2))
		anim:runAction(CCRepeatForever:create(CCSequence:create(action)))
	end

	anim:runAction(CCSequence:createWithTwoActions(CCDelayTime:create(delay), CCCallFunc:create(onDelayOver)))

	return anim
end